In [105]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [138]:
import pandas as pd
import numpy as np
import os

In [107]:
goal_1 = "/content/drive/MyDrive/UNSDG/20260905182847242_safa15-5738@diu.edu.bd/Goal1.xlsx"
goal_2 = "/content/drive/MyDrive/UNSDG/20260905182847242_safa15-5738@diu.edu.bd/Goal2.xlsx"
goal_3 = "/content/drive/MyDrive/UNSDG/20260905182847242_safa15-5738@diu.edu.bd/Goal3.xlsx"
goal_4 = "/content/drive/MyDrive/UNSDG/20260905182847242_safa15-5738@diu.edu.bd/Goal4.xlsx"
goal_5 = "/content/drive/MyDrive/UNSDG/20260905182847242_safa15-5738@diu.edu.bd/Goal5.xlsx"
goal_7 = "/content/drive/MyDrive/UNSDG/20260905182847242_safa15-5738@diu.edu.bd/Goal7.xlsx"
goal_8 = "/content/drive/MyDrive/UNSDG/20260905182847242_safa15-5738@diu.edu.bd/Goal8.xlsx"
goal_9 = "/content/drive/MyDrive/UNSDG/20260905182847242_safa15-5738@diu.edu.bd/Goal9.xlsx"
goal_10 = "/content/drive/MyDrive/UNSDG/20260905182847242_safa15-5738@diu.edu.bd/Goal10.xlsx"
goal_13 = "/content/drive/MyDrive/UNSDG/20260905182847242_safa15-5738@diu.edu.bd/Goal13.xlsx"

In [108]:
df_1 = pd.read_excel(goal_1)

print("For Goal 1")
print("Rows:", len(df_1))
print("Columns:", len(df_1.columns))
print()


df_2 = pd.read_excel(goal_2)

print("For Goal 2")
print("Rows:", len(df_2))
print("Columns:", len(df_2.columns))
print()


df_3 = pd.read_excel(goal_3)

print("For Goal 3")
print("Rows:", len(df_3))
print("Columns:", len(df_3.columns))
print()


df_4 = pd.read_excel(goal_4)

print("For Goal 4")
print("Rows:", len(df_4))
print("Columns:", len(df_4.columns))
print()


df_5 = pd.read_excel(goal_5)

print("For Goal 5")
print("Rows:", len(df_5))
print("Columns:", len(df_5.columns))
print()


df_7 = pd.read_excel(goal_7)

print("For Goal 7")
print("Rows:", len(df_7))
print("Columns:", len(df_7.columns))
print()


df_8 = pd.read_excel(goal_8)

print("For Goal 8")
print("Rows:", len(df_8))
print("Columns:", len(df_8.columns))
print()


df_9 = pd.read_excel(goal_9)

print("For Goal 9")
print("Rows:", len(df_9))
print("Columns:", len(df_9.columns))
print()


df_10 = pd.read_excel(goal_10)

print("For Goal 10")
print("Rows:", len(df_10))
print("Columns:", len(df_10.columns))
print()


df_13 = pd.read_excel(goal_13)

print("For Goal 13")
print("Rows:", len(df_13))
print("Columns:", len(df_13.columns))
print()

For Goal 1
Rows: 18778
Columns: 30

For Goal 2
Rows: 3380
Columns: 30

For Goal 3
Rows: 25755
Columns: 30

For Goal 4
Rows: 2343
Columns: 30

For Goal 5
Rows: 3073
Columns: 30

For Goal 7
Rows: 6540
Columns: 30

For Goal 8
Rows: 25681
Columns: 30

For Goal 9
Rows: 6707
Columns: 30

For Goal 10
Rows: 717
Columns: 30

For Goal 13
Rows: 8832
Columns: 30

In [109]:
print("Columns in df_1:")
print(df_1.columns)
print()

print("Columns in df_2:")
print(df_2.columns)
print()

print("Columns in df_3:")
print(df_3.columns)
print()

print("Columns in df_4:")
print(df_4.columns)
print()

print("Columns in df_5:")
print(df_5.columns)
print()

print("Columns in df_7:")
print(df_7.columns)
print()

print("Columns in df_8:")
print(df_8.columns)
print()

print("Columns in df_9:")
print(df_9.columns)
print()

print("Columns in df_10:")
print(df_10.columns)
print()

print("Columns in df_13:")
print(df_13.columns)

Columns in df_1:
Index(['Goal', 'Target', 'Indicator', 'SeriesCode', 'SeriesDescription',
       'GeoAreaCode', 'GeoAreaName', 'TimePeriod', 'Value', 'Time_Detail',
       'TimeCoverage', 'UpperBound', 'LowerBound', 'BasePeriod', 'Source',
       'GeoInfoUrl', 'FootNote', 'Age', 'Freq', 'Location', 'Nature', 'Sex',
       'Units', 'Education level', 'Type of skill', 'Disability status',
       'Hazard type', 'Reporting Type', 'Quantile', 'Observation Status'],
      dtype='object')

Columns in df_2:
Index(['Goal', 'Target', 'Indicator', 'SeriesCode', 'SeriesDescription',
       'GeoAreaCode', 'GeoAreaName', 'TimePeriod', 'Value', 'Time_Detail',
       'TimeCoverage', 'UpperBound', 'LowerBound', 'BasePeriod', 'Source',
       'GeoInfoUrl', 'FootNote', 'Age', 'Freq', 'Location', 'Nature', 'Sex',
       'Units', 'Education level', 'Type of skill', 'Disability status',
       'Hazard type', 'Reporting Type', 'Quantile', 'Observation Status'],
      dtype='object')

Columns in df_3:
Index(['Goal', 'Target', 'Indicator', 'SeriesCode', 'SeriesDescription',
       'GeoAreaCode', 'GeoAreaName', 'TimePeriod', 'Value', 'Time_Detail',
       'TimeCoverage', 'UpperBound', 'LowerBound', 'BasePeriod', 'Source',
       'GeoInfoUrl', 'FootNote', 'Age', 'Freq', 'Location', 'Nature', 'Sex',
       'Units', 'Education level', 'Type of skill', 'Disability status',
       'Hazard type', 'Reporting Type', 'Quantile', 'Observation Status'],
      dtype='object')

Columns in df_4:
Index(['Goal', 'Target', 'Indicator', 'SeriesCode', 'SeriesDescription',
       'GeoAreaCode', 'GeoAreaName', 'TimePeriod', 'Value', 'Time_Detail',
       'TimeCoverage', 'UpperBound', 'LowerBound', 'BasePeriod', 'Source',
       'GeoInfoUrl', 'FootNote', 'Age', 'Freq', 'Location', 'Nature', 'Sex',
       'Units', 'Education level', 'Type of skill', 'Disability status',
       'Hazard type', 'Reporting Type', 'Quantile', 'Observation Status'],
      dtype='object')

Columns in df_5:
Index(['Goal', 'Target', 'Indicator', 'SeriesCode', 'SeriesDescription',
       'GeoAreaCode', 'GeoAreaName', 'TimePeriod', 'Value', 'Time_Detail',
       'TimeCoverage', 'UpperBound', 'LowerBound', 'BasePeriod', 'Source',
       'GeoInfoUrl', 'FootNote', 'Age', 'Freq', 'Location', 'Nature', 'Sex',
       'Units', 'Education level', 'Type of skill', 'Disability status',
       'Hazard type', 'Reporting Type', 'Quantile', 'Observation Status'],
      dtype='object')

Columns in df_7:
Index(['Goal', 'Target', 'Indicator', 'SeriesCode', 'SeriesDescription',
       'GeoAreaCode', 'GeoAreaName', 'TimePeriod', 'Value', 'Time_Detail',
       'TimeCoverage', 'UpperBound', 'LowerBound', 'BasePeriod', 'Source',
       'GeoInfoUrl', 'FootNote', 'Age', 'Freq', 'Location', 'Nature', 'Sex',
       'Units', 'Education level', 'Type of skill', 'Disability status',
       'Hazard type', 'Reporting Type', 'Quantile', 'Observation Status'],
      dtype='object')

Columns in df_8:
Index(['Goal', 'Target', 'Indicator', 'SeriesCode', 'SeriesDescription',
       'GeoAreaCode', 'GeoAreaName', 'TimePeriod', 'Value', 'Time_Detail',
       'TimeCoverage', 'UpperBound', 'LowerBound', 'BasePeriod', 'Source',
       'GeoInfoUrl', 'FootNote', 'Age', 'Freq', 'Location', 'Nature', 'Sex',
       'Units', 'Education level', 'Type of skill', 'Disability status',
       'Hazard type', 'Reporting Type', 'Quantile', 'Observation Status'],
      dtype='object')

Columns in df_9:
Index(['Goal', 'Target', 'Indicator', 'SeriesCode', 'SeriesDescription',
       'GeoAreaCode', 'GeoAreaName', 'TimePeriod', 'Value', 'Time_Detail',
       'TimeCoverage', 'UpperBound', 'LowerBound', 'BasePeriod', 'Source',
       'GeoInfoUrl', 'FootNote', 'Age', 'Freq', 'Location', 'Nature', 'Sex',
       'Units', 'Education level', 'Type of skill', 'Disability status',
       'Hazard type', 'Reporting Type', 'Quantile', 'Observation Status'],
      dtype='object')

Columns in df_10:
Index(['Goal', 'Target', 'Indicator', 'SeriesCode', 'SeriesDescription',
       'GeoAreaCode', 'GeoAreaName', 'TimePeriod', 'Value', 'Time_Detail',
       'TimeCoverage', 'UpperBound', 'LowerBound', 'BasePeriod', 'Source',
       'GeoInfoUrl', 'FootNote', 'Age', 'Freq', 'Location', 'Nature', 'Sex',
       'Units', 'Education level', 'Type of skill', 'Disability status',
       'Hazard type', 'Reporting Type', 'Quantile', 'Observation Status'],
      dtype='object')

Columns in df_13:
Index(['Goal', 'Target', 'Indicator', 'SeriesCode', 'SeriesDescription',
       'GeoAreaCode', 'GeoAreaName', 'TimePeriod', 'Value', 'Time_Detail',
       'TimeCoverage', 'UpperBound', 'LowerBound', 'BasePeriod', 'Source',
       'GeoInfoUrl', 'FootNote', 'Age', 'Freq', 'Location', 'Nature', 'Sex',
       'Units', 'Education level', 'Type of skill', 'Disability status',
       'Hazard type', 'Reporting Type', 'Quantile', 'Observation Status'],
      dtype='object')

In [110]:
print("Goal 1:", df_1["SeriesCode"].nunique(), "unique series")
print("Goal 2:", df_2["SeriesCode"].nunique(), "unique series")
print("Goal 3:", df_3["SeriesCode"].nunique(), "unique series")
print("Goal 4:", df_4["SeriesCode"].nunique(), "unique series")
print("Goal 5:", df_5["SeriesCode"].nunique(), "unique series")
print("Goal 7:", df_7["SeriesCode"].nunique(), "unique series")
print("Goal 8:", df_8["SeriesCode"].nunique(), "unique series")
print("Goal 9:", df_9["SeriesCode"].nunique(), "unique series")
print("Goal 10:", df_10["SeriesCode"].nunique(), "unique series")
print("Goal 13:", df_13["SeriesCode"].nunique(), "unique series")

Goal 1: 4 unique series
Goal 2: 2 unique series
Goal 3: 5 unique series
Goal 4: 1 unique series
Goal 5: 4 unique series
Goal 7: 1 unique series
Goal 8: 4 unique series
Goal 9: 4 unique series
Goal 10: 1 unique series
Goal 13: 10 unique series

In [111]:
all_goals = pd.concat(
    [df_1, df_2, df_3, df_4, df_5,
     df_7, df_8, df_9, df_10, df_13],
    ignore_index=True
)

print("Rows:", len(all_goals))
print("Columns:", len(all_goals.columns))

Rows: 101806
Columns: 30

In [112]:
print(all_goals["Goal"].value_counts().sort_index())

Goal
1     18778
2      3380
3     25755
4      2343
5      3073
7      6540
8     25681
9      6707
10      717
13     8832
Name: count, dtype: int64

In [113]:
all_goals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101806 entries, 0 to 101805
Data columns (total 30 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Goal                101806 non-null  int64
 1   Target              101806 non-null  object
 2   Indicator           101806 non-null  object
 3   SeriesCode          101806 non-null  object
 4   SeriesDescription   101806 non-null  object
 5   GeoAreaCode         101806 non-null  int64
 6   GeoAreaName         101806 non-null  object
 7   TimePeriod          101806 non-null  int64
 8   Value               101010 non-null  object
 9   Time_Detail         101806 non-null  object
 10  TimeCoverage        0 non-null       float64
 11  UpperBound          25755 non-null   float64
 12  LowerBound          25755 non-null   float64
 13  BasePeriod          4673 non-null    float64
 14  Source              101774 non-null  object
 15  GeoInfoUrl          0 non-null       float64
 16  FootNote            47870 non-null   object
 17  Age                 60003 non-null   object
 18  Freq                0 non-null       float64
 19  Location            22742 non-null   object
 20  Nature              101010 non-null  object
 21  Sex                 64101 non-null   object
 22  Units               101806 non-null  object
 23  Education level     2343 non-null    object
 24  Type of skill       2343 non-null    object
 25  Disability status   8678 non-null    object
 26  Hazard type         0 non-null       float64
 27  Reporting Type      101806 non-null  object
 28  Quantile            717 non-null     object
 29  Observation Status  34710 non-null   object
dtypes: float64(7), int64(3), object(20)
memory usage: 23.3+ MB

In [114]:
missing = all_goals.isna().sum().sort_values(ascending=False)

print(missing)

TimeCoverage          101806
GeoInfoUrl            101806
Freq                  101806
Hazard type           101806
Quantile              101089
Type of skill          99463
Education level        99463
BasePeriod             97133
Disability status      93128
Location               79064
UpperBound             76051
LowerBound             76051
Observation Status     67096
FootNote               53936
Age                    41803
Sex                    37705
Nature                   796
Value                    796
Source                    32
TimePeriod                 0
SeriesDescription          0
GeoAreaCode                0
Goal                       0
GeoAreaName                0
Time_Detail                0
Target                     0
Indicator                  0
SeriesCode                 0
Units                      0
Reporting Type             0
dtype: int64

In [115]:
all_goals = all_goals.drop(
    columns=["TimeCoverage", "GeoInfoUrl", "Freq", "Hazard type"]
)

print("Rows:", len(all_goals))
print("Columns:", len(all_goals.columns))

Rows: 101806
Columns: 26

In [116]:
all_goals["Value"] = pd.to_numeric(
    all_goals["Value"],
    errors="coerce"
)

print(all_goals["Value"].dtype)
print("Missing Value:", all_goals["Value"].isna().sum())

float64
Missing Value: 1533

In [117]:
all_goals = pd.concat(
    [df_1, df_2, df_3, df_4, df_5,
     df_7, df_8, df_9, df_10, df_13],
    ignore_index=True
)

print(all_goals["Value"].dtype)
print(all_goals["Value"].isna().sum())

object
796

In [118]:
print("Unique values:", all_goals["Value"].nunique())

Unique values: 43386

In [119]:
non_numeric = pd.to_numeric(all_goals["Value"], errors="coerce").isna()

print(all_goals.loc[non_numeric, "Value"].unique())

['<2.5' nan '<0.1']

In [120]:
all_goals["Value_numeric"] = pd.to_numeric(
    all_goals["Value"],
    errors="coerce"
)

print(all_goals[["Value", "Value_numeric"]].head(20))

       Value  Value_numeric
0        1.1        1.10000
1        1.1        1.10000
2        1.4        1.40000
3        1.0        1.00000
4    1.60093        1.60093
5    0.47185        0.47185
6    1.00619        1.00619
7    1.01378        1.01378
8    0.97459        0.97459
9        0.3        0.30000
10       0.3        0.30000
11   0.43253        0.43253
12   0.36285        0.36285
13   0.14441        0.14441
14   0.36964        0.36964
15   0.31201        0.31201
16      39.3       39.30000
17  45.11272       45.11272
18  33.23289       33.23289
19  34.17076       34.17076

In [121]:
print("Countries:", all_goals["GeoAreaName"].nunique())
print("Years:", all_goals["TimePeriod"].min(), "to", all_goals["TimePeriod"].max())
print("Indicators:", all_goals["Indicator"].nunique())
print("Series:", all_goals["SeriesCode"].nunique())

print("\nObservations by Goal:")
print(all_goals["Goal"].value_counts().sort_index())

print("\nCountries by Goal:")
print(all_goals.groupby("Goal")["GeoAreaName"].nunique().sort_index())

print("\nYears by Goal:")
print(all_goals.groupby("Goal")["TimePeriod"].agg(["min", "max"]))

Countries: 239
Years: 2015 to 2024
Indicators: 12
Series: 36

Observations by Goal:
Goal
1     18778
2      3380
3     25755
4      2343
5      3073
7      6540
8     25681
9      6707
10      717
13     8832
Name: count, dtype: int64

Countries by Goal:
Goal
1     232
2     169
3     201
4     131
5     167
7     218
8     193
9     235
10    150
13    163
Name: GeoAreaName, dtype: int64

Years by Goal:
       min   max
Goal
1     2015  2024
2     2015  2024
3     2015  2024
4     2015  2024
5     2015  2024
7     2015  2024
8     2015  2024
9     2015  2024
10    2015  2024
13    2015  2024

In [122]:
series_summary = (
    all_goals
    .groupby(["Goal", "SeriesCode", "SeriesDescription"])
    .agg(
        observations=("Value", "size"),
        countries=("GeoAreaName", "nunique"),
        years=("TimePeriod", "nunique"),
        first_year=("TimePeriod", "min"),
        last_year=("TimePeriod", "max"),
        missing_values=("Value_numeric", lambda x: x.isna().sum())
    )
    .reset_index()
)

print(series_summary.to_string(index=False))

 Goal           SeriesCode                                                                                            SeriesDescription  observations  countries  years  first_year  last_year  missing_values
    1          SI_POV_DAY1                                                Proportion of population below international poverty line (%)          4673        150     10        2015       2024               0
    1          SI_POV_EMP1                                     Employed population below international poverty line, by sex and age (%)          2576         63     10        2015       2024               0
    1       SP_ACS_BSRVH2O                                Proportion of population using basic drinking water services, by location (%)          5809        231     10        2015       2024               0
    1       SP_ACS_BSRVSAN                                    Proportion of population using basic sanitation services, by location (%)          5720        232     10        2015       2024               0
    2          SN_ITK_DEFC                                                                           Prevalence of undernourishment (%)          1690        169     10        2015       2024             594
    2         SN_ITK_DEFCN                                                                   Number of undernourished people (millions)          1690        169     10        2015       2024             753
    3          SH_DYN_IMRT                                                         Infant mortality rate (deaths per 1,000 live births)          6000        200     10        2015       2024               0
    3         SH_DYN_IMRTN                                                                                       Infant deaths (number)          6000        200     10        2015       2024               0
    3          SH_DYN_MORT                                             Under-five mortality rate, by sex (deaths per 1,000 live births)          6000        200     10        2015       2024               0
    3         SH_DYN_MORTN                                                                                   Under-five deaths (number)          6000        200     10        2015       2024               0
    3          SH_STA_MORT                                                                                     Maternal mortality ratio          1755        195      9        2015       2023               0
    4          SE_TOT_PRFL Proportion of children and young people achieving a minimum proficiency level in reading and mathematics (%)          2343        131      9        2015       2024               0
    5          IC_GEN_MGTL                                                  Proportion of women in managerial positions - 13th ICLS (%)          1045        167     10        2015       2024               0
    5   IC_GEN_MGTL_19ICLS                                                  Proportion of women in managerial positions - 19th ICLS (%)           649        112     10        2015       2024               0
    5          IC_GEN_MGTN                                Proportion of women in senior and middle management positions - 13th ICLS (%)           876        146     10        2015       2024               0
    5   IC_GEN_MGTN_19ICLS                                Proportion of women in senior and middle management positions - 19th ICLS (%)           503         92     10        2015       2024               0
    7          EG_ACS_ELEC                                      Proportion of population with access to electricity, by urban/rural (%)          6540        218     10        2015       2024             186
    8           SL_TLF_UEM                                                            Unemployment rate, by sex and age - 13th ICLS (%)         10657        193     10        2015       2024               0
    8        SL_TLF_UEMDIS                                                     Unemployment rate, by sex and disability - 13th ICLS (%)          4895        122     10        2015       2024               0
    8 SL_TLF_UEMDIS_19ICLS                                                     Unemployment rate, by sex and disability - 19th ICLS (%)          3783         84     10        2015       2024               0
    8    SL_TLF_UEM_19ICLS                                                            Unemployment rate, by sex and age - 19th ICLS (%)          6346        124     10        2015       2024               0
    9        IT_MOB_2GNTWK                                         Proportion of population covered by at least a 2G mobile network (%)          1953        225     10        2015       2024               0
    9        IT_MOB_3GNTWK                                         Proportion of population covered by at least a 3G mobile network (%)          2078        227     10        2015       2024               0
    9        IT_MOB_4GNTWK                                         Proportion of population covered by at least a 4G mobile network (%)          2005        222     10        2015       2024               0
    9        IT_MOB_5GNTWK                                         Proportion of population covered by at least a 5G mobile network (%)           671        221      7        2018       2024               0
   10          SI_POV_50MI                                            Proportion of people living below 50 percent of median income (%)           717        150     10        2015       2024               0
   13         VC_DSR_AFFCT                                                               Number of people affected by disaster (number)           971        154     10        2015       2024               0
   13          VC_DSR_DAFF                  Number of directly affected persons attributed to disasters per 100,000 population (number)           971        154     10        2015       2024               0
   13         VC_DSR_IJILN                                             Number of injured or ill people attributed to disasters (number)           883        147     10        2015       2024               0
   13          VC_DSR_MISS                                                           Number of missing persons due to disaster (number)           796        139     10        2015       2024               0
   13          VC_DSR_MMHN                                        Number of deaths and missing persons attributed to disasters (number)          1053        163     10        2015       2024               0
   13          VC_DSR_MORT                                                                    Number of deaths due to disaster (number)          1041        161     10        2015       2024               0
   13          VC_DSR_MTMP                 Number of deaths and missing persons attributed to disasters per 100,000 population (number)          1053        163     10        2015       2024               0
   13          VC_DSR_PDAN                               Number of people whose damaged dwellings were attributed to disasters (number)           789        141     10        2015       2024               0
   13          VC_DSR_PDLN             Number of people whose livelihoods were disrupted or destroyed, attributed to disasters (number)           580        114     10        2015       2024               0
   13          VC_DSR_PDYN                             Number of people whose destroyed dwellings were attributed to disasters (number)           695        135     10        2015       2024               0

In [123]:
missing_summary = series_summary[
    series_summary["missing_values"] > 0
].sort_values("missing_values", ascending=False)

missing_summary

,Goal,SeriesCode,SeriesDescription,observations,countries,years,first_year,last_year,missing_values
5,2,SN_ITK_DEFCN,Number of undernourished people (millions),1690,169,10,2015,2024,753
4,2,SN_ITK_DEFC,Prevalence of undernourishment (%),1690,169,10,2015,2024,594
16,7,EG_ACS_ELEC,Proportion of population with access to electr...,6540,218,10,2015,2024,186

In [124]:
missing_summary["missing_pct"] = (
    missing_summary["missing_values"]/ missing_summary["observations"] * 100
)

missing_summary

,Goal,SeriesCode,SeriesDescription,observations,countries,years,first_year,last_year,missing_values,missing_pct
5,2,SN_ITK_DEFCN,Number of undernourished people (millions),1690,169,10,2015,2024,753,44.556213
4,2,SN_ITK_DEFC,Prevalence of undernourishment (%),1690,169,10,2015,2024,594,35.147929
16,7,EG_ACS_ELEC,Proportion of population with access to electr...,6540,218,10,2015,2024,186,2.844037

In [125]:
missing_by_country = (
    .groupby(["SeriesCode", "GeoAreaName"])
    all_goals[all_goals["Value_numeric"].isna()]
    .size()
    .reset_index(name="missing_values")
    .sort_values(["SeriesCode", "missing_values"], ascending=[True, False])
)

missing_by_country

,SeriesCode,GeoAreaName,missing_values
0,EG_ACS_ELEC,American Samoa,30
2,EG_ACS_ELEC,Anguilla,20
6,EG_ACS_ELEC,Democratic People's Republic of Korea,20
11,EG_ACS_ELEC,Grenada,20
5,EG_ACS_ELEC,Cook Islands,10
8,EG_ACS_ELEC,Dominica,10
15,EG_ACS_ELEC,Libya,10
18,EG_ACS_ELEC,Mauritania,10
22,EG_ACS_ELEC,Niue,10
1,EG_ACS_ELEC,Angola,7
3,EG_ACS_ELEC,Burkina Faso,7
13,EG_ACS_ELEC,Kiribati,7
12,EG_ACS_ELEC,Haiti,4
20,EG_ACS_ELEC,Naoero,3
21,EG_ACS_ELEC,Nepal,3
23,EG_ACS_ELEC,Panama,3
10,EG_ACS_ELEC,Gambia,2
16,EG_ACS_ELEC,Madagascar,2
4,EG_ACS_ELEC,Chad,1
7,EG_ACS_ELEC,Djibouti,1
9,EG_ACS_ELEC,Gabon,1
14,EG_ACS_ELEC,Lesotho,1
17,EG_ACS_ELEC,Mali,1
19,EG_ACS_ELEC,Namibia,1
24,EG_ACS_ELEC,Somalia,1
25,EG_ACS_ELEC,Yemen,1
27,SN_ITK_DEFC,Armenia,10
28,SN_ITK_DEFC,Australia,10
29,SN_ITK_DEFC,Austria,10
30,SN_ITK_DEFC,Azerbaijan,10
32,SN_ITK_DEFC,Belarus,10
33,SN_ITK_DEFC,Belgium,10
34,SN_ITK_DEFC,Bosnia and Herzegovina,10
37,SN_ITK_DEFC,Canada,10
39,SN_ITK_DEFC,China,10
40,SN_ITK_DEFC,Costa Rica,10
41,SN_ITK_DEFC,Croatia,10
43,SN_ITK_DEFC,Cyprus,10
44,SN_ITK_DEFC,Czechia,10
46,SN_ITK_DEFC,Denmark,10
48,SN_ITK_DEFC,Estonia,10
49,SN_ITK_DEFC,Finland,10
50,SN_ITK_DEFC,France,10
53,SN_ITK_DEFC,Germany,10
54,SN_ITK_DEFC,Greece,10
56,SN_ITK_DEFC,Hungary,10
57,SN_ITK_DEFC,Iceland,10
58,SN_ITK_DEFC,Ireland,10
59,SN_ITK_DEFC,Israel,10
60,SN_ITK_DEFC,Italy,10
61,SN_ITK_DEFC,Japan,10
63,SN_ITK_DEFC,Kuwait,10
64,SN_ITK_DEFC,Latvia,10
65,SN_ITK_DEFC,Lithuania,10
66,SN_ITK_DEFC,Luxembourg,10
68,SN_ITK_DEFC,Malta,10
70,SN_ITK_DEFC,Montenegro,10
71,SN_ITK_DEFC,Netherlands (Kingdom of the),10
72,SN_ITK_DEFC,New Zealand,10
74,SN_ITK_DEFC,North Macedonia,10
75,SN_ITK_DEFC,Norway,10
77,SN_ITK_DEFC,Poland,10
78,SN_ITK_DEFC,Portugal,10
79,SN_ITK_DEFC,Republic of Korea,10
81,SN_ITK_DEFC,Romania,10
82,SN_ITK_DEFC,Russian Federation,10
83,SN_ITK_DEFC,Saudi Arabia,10
84,SN_ITK_DEFC,Serbia,10
86,SN_ITK_DEFC,Slovenia,10
88,SN_ITK_DEFC,Spain,10
90,SN_ITK_DEFC,Sweden,10
91,SN_ITK_DEFC,Switzerland,10
93,SN_ITK_DEFC,Türkiye,10
96,SN_ITK_DEFC,United Kingdom of Great Britain and Northern I...,10
97,SN_ITK_DEFC,United States of America,10
98,SN_ITK_DEFC,Uruguay,10
99,SN_ITK_DEFC,Uzbekistan,10
42,SN_ITK_DEFC,Cuba,8
80,SN_ITK_DEFC,Republic of Moldova,8
26,SN_ITK_DEFC,Algeria,6
35,SN_ITK_DEFC,Brazil,6
45,SN_ITK_DEFC,Democratic People's Republic of Korea,6
85,SN_ITK_DEFC,Seychelles,5
87,SN_ITK_DEFC,South Sudan,5
36,SN_ITK_DEFC,Bulgaria,4
38,SN_ITK_DEFC,Chile,4
55,SN_ITK_DEFC,Guyana,4
62,SN_ITK_DEFC,Kazakhstan,4
67,SN_ITK_DEFC,Malaysia,4
95,SN_ITK_DEFC,United Arab Emirates,4
89,SN_ITK_DEFC,Sudan,3
69,SN_ITK_DEFC,Mongolia,2
73,SN_ITK_DEFC,Nicaragua,2
92,SN_ITK_DEFC,Tunisia,2
94,SN_ITK_DEFC,Ukraine,2
31,SN_ITK_DEFC,Barbados,1
47,SN_ITK_DEFC,Dominican Republic,1
51,SN_ITK_DEFC,French Polynesia,1
52,SN_ITK_DEFC,Georgia,1
76,SN_ITK_DEFC,Paraguay,1
101,SN_ITK_DEFCN,Armenia,10
102,SN_ITK_DEFCN,Australia,10
103,SN_ITK_DEFCN,Austria,10
104,SN_ITK_DEFCN,Azerbaijan,10
105,SN_ITK_DEFCN,Barbados,10
106,SN_ITK_DEFCN,Belarus,10
107,SN_ITK_DEFCN,Belgium,10
108,SN_ITK_DEFCN,Belize,10
109,SN_ITK_DEFCN,Bosnia and Herzegovina,10
112,SN_ITK_DEFCN,Cabo Verde,10
113,SN_ITK_DEFCN,Canada,10
115,SN_ITK_DEFCN,China,10
117,SN_ITK_DEFCN,Costa Rica,10
118,SN_ITK_DEFCN,Croatia,10
120,SN_ITK_DEFCN,Cyprus,10
121,SN_ITK_DEFCN,Czechia,10
123,SN_ITK_DEFCN,Denmark,10
124,SN_ITK_DEFCN,Dominica,10
126,SN_ITK_DEFCN,Estonia,10
127,SN_ITK_DEFCN,Fiji,10
128,SN_ITK_DEFCN,Finland,10
129,SN_ITK_DEFCN,France,10
130,SN_ITK_DEFCN,French Polynesia,10
132,SN_ITK_DEFCN,Germany,10
133,SN_ITK_DEFCN,Greece,10
134,SN_ITK_DEFCN,Guyana,10
135,SN_ITK_DEFCN,Hungary,10
136,SN_ITK_DEFCN,Iceland,10
137,SN_ITK_DEFCN,Ireland,10
138,SN_ITK_DEFCN,Israel,10
139,SN_ITK_DEFCN,Italy,10
140,SN_ITK_DEFCN,Japan,10
142,SN_ITK_DEFCN,Kiribati,10
143,SN_ITK_DEFCN,Kuwait,10
144,SN_ITK_DEFCN,Latvia,10
145,SN_ITK_DEFCN,Lithuania,10
146,SN_ITK_DEFCN,Luxembourg,10
148,SN_ITK_DEFCN,Malta,10
149,SN_ITK_DEFCN,Mauritius,10
151,SN_ITK_DEFCN,Montenegro,10
152,SN_ITK_DEFCN,Netherlands (Kingdom of the),10
153,SN_ITK_DEFCN,New Caledonia,10
154,SN_ITK_DEFCN,New Zealand,10
156,SN_ITK_DEFCN,North Macedonia,10
157,SN_ITK_DEFCN,Norway,10
159,SN_ITK_DEFCN,Poland,10
160,SN_ITK_DEFCN,Portugal,10
161,SN_ITK_DEFCN,Republic of Korea,10
163,SN_ITK_DEFCN,Romania,10
164,SN_ITK_DEFCN,Russian Federation,10
165,SN_ITK_DEFCN,Saint Vincent and the Grenadines,10
166,SN_ITK_DEFCN,Samoa,10
167,SN_ITK_DEFCN,Sao Tome and Principe,10
168,SN_ITK_DEFCN,Saudi Arabia,10
169,SN_ITK_DEFCN,Serbia,10
170,SN_ITK_DEFCN,Seychelles,10
171,SN_ITK_DEFCN,Slovenia,10
173,SN_ITK_DEFCN,Spain,10
175,SN_ITK_DEFCN,Suriname,10
176,SN_ITK_DEFCN,Sweden,10
177,SN_ITK_DEFCN,Switzerland,10
180,SN_ITK_DEFCN,Türkiye,10
183,SN_ITK_DEFCN,United Kingdom of Great Britain and Northern I...,10
184,SN_ITK_DEFCN,United States of America,10
185,SN_ITK_DEFCN,Uruguay,10
186,SN_ITK_DEFCN,Uzbekistan,10
187,SN_ITK_DEFCN,Vanuatu,10
162,SN_ITK_DEFCN,Republic of Moldova,9
119,SN_ITK_DEFCN,Cuba,8
100,SN_ITK_DEFCN,Algeria,6
110,SN_ITK_DEFCN,Brazil,6
122,SN_ITK_DEFCN,Democratic People's Republic of Korea,6
172,SN_ITK_DEFCN,South Sudan,5
111,SN_ITK_DEFCN,Bulgaria,4
114,SN_ITK_DEFCN,Chile,4
116,SN_ITK_DEFCN,Comoros,4
141,SN_ITK_DEFCN,Kazakhstan,4
147,SN_ITK_DEFCN,Malaysia,4
178,SN_ITK_DEFCN,Trinidad and Tobago,4
182,SN_ITK_DEFCN,United Arab Emirates,4
150,SN_ITK_DEFCN,Mongolia,3
174,SN_ITK_DEFCN,Sudan,3
155,SN_ITK_DEFCN,Nicaragua,2
179,SN_ITK_DEFCN,Tunisia,2
181,SN_ITK_DEFCN,Ukraine,2
125,SN_ITK_DEFCN,Dominican Republic,1
131,SN_ITK_DEFCN,Georgia,1
158,SN_ITK_DEFCN,Paraguay,1

In [126]:
pd.set_option("display.max_rows", None)

missing_by_country

,SeriesCode,GeoAreaName,missing_values
0,EG_ACS_ELEC,American Samoa,30
2,EG_ACS_ELEC,Anguilla,20
6,EG_ACS_ELEC,Democratic People's Republic of Korea,20
11,EG_ACS_ELEC,Grenada,20
5,EG_ACS_ELEC,Cook Islands,10
8,EG_ACS_ELEC,Dominica,10
15,EG_ACS_ELEC,Libya,10
18,EG_ACS_ELEC,Mauritania,10
22,EG_ACS_ELEC,Niue,10
1,EG_ACS_ELEC,Angola,7
3,EG_ACS_ELEC,Burkina Faso,7
13,EG_ACS_ELEC,Kiribati,7
12,EG_ACS_ELEC,Haiti,4
20,EG_ACS_ELEC,Naoero,3
21,EG_ACS_ELEC,Nepal,3
23,EG_ACS_ELEC,Panama,3
10,EG_ACS_ELEC,Gambia,2
16,EG_ACS_ELEC,Madagascar,2
4,EG_ACS_ELEC,Chad,1
7,EG_ACS_ELEC,Djibouti,1
9,EG_ACS_ELEC,Gabon,1
14,EG_ACS_ELEC,Lesotho,1
17,EG_ACS_ELEC,Mali,1
19,EG_ACS_ELEC,Namibia,1
24,EG_ACS_ELEC,Somalia,1
25,EG_ACS_ELEC,Yemen,1
27,SN_ITK_DEFC,Armenia,10
28,SN_ITK_DEFC,Australia,10
29,SN_ITK_DEFC,Austria,10
30,SN_ITK_DEFC,Azerbaijan,10
32,SN_ITK_DEFC,Belarus,10
33,SN_ITK_DEFC,Belgium,10
34,SN_ITK_DEFC,Bosnia and Herzegovina,10
37,SN_ITK_DEFC,Canada,10
39,SN_ITK_DEFC,China,10
40,SN_ITK_DEFC,Costa Rica,10
41,SN_ITK_DEFC,Croatia,10
43,SN_ITK_DEFC,Cyprus,10
44,SN_ITK_DEFC,Czechia,10
46,SN_ITK_DEFC,Denmark,10
48,SN_ITK_DEFC,Estonia,10
49,SN_ITK_DEFC,Finland,10
50,SN_ITK_DEFC,France,10
53,SN_ITK_DEFC,Germany,10
54,SN_ITK_DEFC,Greece,10
56,SN_ITK_DEFC,Hungary,10
57,SN_ITK_DEFC,Iceland,10
58,SN_ITK_DEFC,Ireland,10
59,SN_ITK_DEFC,Israel,10
60,SN_ITK_DEFC,Italy,10
61,SN_ITK_DEFC,Japan,10
63,SN_ITK_DEFC,Kuwait,10
64,SN_ITK_DEFC,Latvia,10
65,SN_ITK_DEFC,Lithuania,10
66,SN_ITK_DEFC,Luxembourg,10
68,SN_ITK_DEFC,Malta,10
70,SN_ITK_DEFC,Montenegro,10
71,SN_ITK_DEFC,Netherlands (Kingdom of the),10
72,SN_ITK_DEFC,New Zealand,10
74,SN_ITK_DEFC,North Macedonia,10
75,SN_ITK_DEFC,Norway,10
77,SN_ITK_DEFC,Poland,10
78,SN_ITK_DEFC,Portugal,10
79,SN_ITK_DEFC,Republic of Korea,10
81,SN_ITK_DEFC,Romania,10
82,SN_ITK_DEFC,Russian Federation,10
83,SN_ITK_DEFC,Saudi Arabia,10
84,SN_ITK_DEFC,Serbia,10
86,SN_ITK_DEFC,Slovenia,10
88,SN_ITK_DEFC,Spain,10
90,SN_ITK_DEFC,Sweden,10
91,SN_ITK_DEFC,Switzerland,10
93,SN_ITK_DEFC,Türkiye,10
96,SN_ITK_DEFC,United Kingdom of Great Britain and Northern I...,10
97,SN_ITK_DEFC,United States of America,10
98,SN_ITK_DEFC,Uruguay,10
99,SN_ITK_DEFC,Uzbekistan,10
42,SN_ITK_DEFC,Cuba,8
80,SN_ITK_DEFC,Republic of Moldova,8
26,SN_ITK_DEFC,Algeria,6
35,SN_ITK_DEFC,Brazil,6
45,SN_ITK_DEFC,Democratic People's Republic of Korea,6
85,SN_ITK_DEFC,Seychelles,5
87,SN_ITK_DEFC,South Sudan,5
36,SN_ITK_DEFC,Bulgaria,4
38,SN_ITK_DEFC,Chile,4
55,SN_ITK_DEFC,Guyana,4
62,SN_ITK_DEFC,Kazakhstan,4
67,SN_ITK_DEFC,Malaysia,4
95,SN_ITK_DEFC,United Arab Emirates,4
89,SN_ITK_DEFC,Sudan,3
69,SN_ITK_DEFC,Mongolia,2
73,SN_ITK_DEFC,Nicaragua,2
92,SN_ITK_DEFC,Tunisia,2
94,SN_ITK_DEFC,Ukraine,2
31,SN_ITK_DEFC,Barbados,1
47,SN_ITK_DEFC,Dominican Republic,1
51,SN_ITK_DEFC,French Polynesia,1
52,SN_ITK_DEFC,Georgia,1
76,SN_ITK_DEFC,Paraguay,1
101,SN_ITK_DEFCN,Armenia,10
102,SN_ITK_DEFCN,Australia,10
103,SN_ITK_DEFCN,Austria,10
104,SN_ITK_DEFCN,Azerbaijan,10
105,SN_ITK_DEFCN,Barbados,10
106,SN_ITK_DEFCN,Belarus,10
107,SN_ITK_DEFCN,Belgium,10
108,SN_ITK_DEFCN,Belize,10
109,SN_ITK_DEFCN,Bosnia and Herzegovina,10
112,SN_ITK_DEFCN,Cabo Verde,10
113,SN_ITK_DEFCN,Canada,10
115,SN_ITK_DEFCN,China,10
117,SN_ITK_DEFCN,Costa Rica,10
118,SN_ITK_DEFCN,Croatia,10
120,SN_ITK_DEFCN,Cyprus,10
121,SN_ITK_DEFCN,Czechia,10
123,SN_ITK_DEFCN,Denmark,10
124,SN_ITK_DEFCN,Dominica,10
126,SN_ITK_DEFCN,Estonia,10
127,SN_ITK_DEFCN,Fiji,10
128,SN_ITK_DEFCN,Finland,10
129,SN_ITK_DEFCN,France,10
130,SN_ITK_DEFCN,French Polynesia,10
132,SN_ITK_DEFCN,Germany,10
133,SN_ITK_DEFCN,Greece,10
134,SN_ITK_DEFCN,Guyana,10
135,SN_ITK_DEFCN,Hungary,10
136,SN_ITK_DEFCN,Iceland,10
137,SN_ITK_DEFCN,Ireland,10
138,SN_ITK_DEFCN,Israel,10
139,SN_ITK_DEFCN,Italy,10
140,SN_ITK_DEFCN,Japan,10
142,SN_ITK_DEFCN,Kiribati,10
143,SN_ITK_DEFCN,Kuwait,10
144,SN_ITK_DEFCN,Latvia,10
145,SN_ITK_DEFCN,Lithuania,10
146,SN_ITK_DEFCN,Luxembourg,10
148,SN_ITK_DEFCN,Malta,10
149,SN_ITK_DEFCN,Mauritius,10
151,SN_ITK_DEFCN,Montenegro,10
152,SN_ITK_DEFCN,Netherlands (Kingdom of the),10
153,SN_ITK_DEFCN,New Caledonia,10
154,SN_ITK_DEFCN,New Zealand,10
156,SN_ITK_DEFCN,North Macedonia,10
157,SN_ITK_DEFCN,Norway,10
159,SN_ITK_DEFCN,Poland,10
160,SN_ITK_DEFCN,Portugal,10
161,SN_ITK_DEFCN,Republic of Korea,10
163,SN_ITK_DEFCN,Romania,10
164,SN_ITK_DEFCN,Russian Federation,10
165,SN_ITK_DEFCN,Saint Vincent and the Grenadines,10
166,SN_ITK_DEFCN,Samoa,10
167,SN_ITK_DEFCN,Sao Tome and Principe,10
168,SN_ITK_DEFCN,Saudi Arabia,10
169,SN_ITK_DEFCN,Serbia,10
170,SN_ITK_DEFCN,Seychelles,10
171,SN_ITK_DEFCN,Slovenia,10
173,SN_ITK_DEFCN,Spain,10
175,SN_ITK_DEFCN,Suriname,10
176,SN_ITK_DEFCN,Sweden,10
177,SN_ITK_DEFCN,Switzerland,10
180,SN_ITK_DEFCN,Türkiye,10
183,SN_ITK_DEFCN,United Kingdom of Great Britain and Northern I...,10
184,SN_ITK_DEFCN,United States of America,10
185,SN_ITK_DEFCN,Uruguay,10
186,SN_ITK_DEFCN,Uzbekistan,10
187,SN_ITK_DEFCN,Vanuatu,10
162,SN_ITK_DEFCN,Republic of Moldova,9
119,SN_ITK_DEFCN,Cuba,8
100,SN_ITK_DEFCN,Algeria,6
110,SN_ITK_DEFCN,Brazil,6
122,SN_ITK_DEFCN,Democratic People's Republic of Korea,6
172,SN_ITK_DEFCN,South Sudan,5
111,SN_ITK_DEFCN,Bulgaria,4
114,SN_ITK_DEFCN,Chile,4
116,SN_ITK_DEFCN,Comoros,4
141,SN_ITK_DEFCN,Kazakhstan,4
147,SN_ITK_DEFCN,Malaysia,4
178,SN_ITK_DEFCN,Trinidad and Tobago,4
182,SN_ITK_DEFCN,United Arab Emirates,4
150,SN_ITK_DEFCN,Mongolia,3
174,SN_ITK_DEFCN,Sudan,3
155,SN_ITK_DEFCN,Nicaragua,2
179,SN_ITK_DEFCN,Tunisia,2
181,SN_ITK_DEFCN,Ukraine,2
125,SN_ITK_DEFCN,Dominican Republic,1
131,SN_ITK_DEFCN,Georgia,1
158,SN_ITK_DEFCN,Paraguay,1

In [127]:
elec_missing = all_goals[
    (all_goals["SeriesCode"] == "EG_ACS_ELEC") &
    (all_goals["Value_numeric"].isna())
]

elec_missing

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,TimePeriod,Value,Time_Detail,TimeCoverage,UpperBound,LowerBound,BasePeriod,Source,GeoInfoUrl,FootNote,Age,Freq,Location,Nature,Sex,Units,Education level,Type of skill,Disability status,Hazard type,Reporting Type,Quantile,Observation Status,Value_numeric
53419,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53420,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53421,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53422,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53423,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53424,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53425,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53426,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53427,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53428,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53429,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53430,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53431,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53432,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53433,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53434,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2020,NaN,2020,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53435,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2020,NaN,2020,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53436,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2020,NaN,2020,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53437,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53438,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53439,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53440,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53441,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53442,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53443,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53444,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53445,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53446,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2024,NaN,2024,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53447,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2024,NaN,2024,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53448,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2024,NaN,2024,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53483,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,24,Angola,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53486,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,24,Angola,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53493,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,24,Angola,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53495,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,24,Angola,2020,NaN,2020,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53497,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,24,Angola,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53502,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,24,Angola,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53504,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,24,Angola,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54481,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,148,Chad,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54680,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54684,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54686,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54689,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54692,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54694,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2020,NaN,2020,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54698,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54701,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54705,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54707,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2024,NaN,2024,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54920,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54921,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54923,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54924,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54926,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54927,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54929,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54930,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54932,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54933,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55315,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,262,Djibouti,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55346,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,266,Gabon,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55408,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,270,Gambia,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55412,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,270,Gambia,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55552,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,296,Kiribati,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55557,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,296,Kiribati,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55559,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,296,Kiribati,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55568,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,296,Kiribati,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55570,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,296,Kiribati,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55574,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,296,Kiribati,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55578,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,296,Kiribati,2024,NaN,2024,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55639,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55641,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55643,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55644,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55645,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55647,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55648,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55649,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55652,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55653,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55655,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2020,NaN,2020,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55656,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2020,NaN,2020,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55658,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55659,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55661,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55662,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55663,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55665,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN

In [128]:
pd.set_option("display.max_columns", None)

elec_missing

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,TimePeriod,Value,Time_Detail,TimeCoverage,UpperBound,LowerBound,BasePeriod,Source,GeoInfoUrl,FootNote,Age,Freq,Location,Nature,Sex,Units,Education level,Type of skill,Disability status,Hazard type,Reporting Type,Quantile,Observation Status,Value_numeric
53419,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53420,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53421,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53422,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53423,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53424,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53425,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53426,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53427,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53428,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53429,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53430,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53431,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53432,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53433,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53434,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2020,NaN,2020,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53435,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2020,NaN,2020,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53436,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2020,NaN,2020,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53437,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53438,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53439,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53440,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53441,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53442,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53443,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53444,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53445,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53446,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2024,NaN,2024,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,ALLAREA,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53447,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2024,NaN,2024,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53448,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,16,American Samoa,2024,NaN,2024,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53483,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,24,Angola,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53486,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,24,Angola,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53493,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,24,Angola,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53495,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,24,Angola,2020,NaN,2020,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53497,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,24,Angola,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53502,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,24,Angola,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
53504,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,24,Angola,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54481,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,148,Chad,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54680,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54684,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54686,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54689,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54692,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54694,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2020,NaN,2020,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54698,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54701,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54705,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54707,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,184,Cook Islands,2024,NaN,2024,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54920,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54921,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54923,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54924,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54926,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54927,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54929,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54930,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54932,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
54933,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,212,Dominica,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55315,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,262,Djibouti,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55346,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,266,Gabon,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55408,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,270,Gambia,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55412,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,270,Gambia,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55552,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,296,Kiribati,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55557,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,296,Kiribati,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55559,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,296,Kiribati,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55568,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,296,Kiribati,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55570,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,296,Kiribati,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55574,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,296,Kiribati,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55578,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,296,Kiribati,2024,NaN,2024,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55639,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55641,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2015,NaN,2015,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55643,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55644,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2016,NaN,2016,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55645,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55647,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2017,NaN,2017,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55648,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55649,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2018,NaN,2018,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55652,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55653,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2019,NaN,2019,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55655,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2020,NaN,2020,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55656,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2020,NaN,2020,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55658,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55659,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2021,NaN,2021,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55661,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55662,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2022,NaN,2022,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55663,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,URBAN,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN
55665,7,7.1,7.1.1,EG_ACS_ELEC,Proportion of population with access to electr...,308,Grenada,2023,NaN,2023,NaN,NaN,NaN,NaN,World Bank,NaN,Data nature not available,NaN,NaN,RURAL,NaN,NaN,PERCENT,NaN,NaN,NaN,NaN,G,NaN,NaN,NaN

In [129]:
elec_missing[elec_missing["GeoAreaName"] == "American Samoa"].groupby("TimePeriod").size()

TimePeriod
2015    3
2016    3
2017    3
2018    3
2019    3
2020    3
2021    3
2022    3
2023    3
2024    3
dtype: int64

In [130]:
elec_missing[elec_missing["GeoAreaName"] == "American Samoa"]["Location"].value_counts()

Location
URBAN      10
ALLAREA    10
RURAL      10
Name: count, dtype: int64

In [131]:
# Dimensions that can represent disaggregation in the SDG dataset
dimensions = [
    "Age",
    "Location",
    "Sex",
    "Education level",
    "Type of skill",
    "Disability status",
    "Hazard type",
    "Quantile"
]

print(dimensions)

['Age', 'Location', 'Sex', 'Education level', 'Type of skill', 'Disability status', 'Hazard type', 'Quantile']

In [132]:
for dim in dimensions:
    print(f"\n--- {dim} ---")
    print("Missing:", all_goals[dim].isna().sum())
    print("Unique values:", all_goals[dim].nunique(dropna=False))
    print(all_goals[dim].value_counts(dropna=False))

--- Age ---
Missing: 41803
Unique values: 10
Age
NaN       41803
15+       18383
<1Y       12000
<5Y       12000
15-24      6479
25+        6468
ALLAGE     2967
<15Y        569
65+         569
15-64       568
Name: count, dtype: int64

--- Location ---
Missing: 79064
Unique values: 4
Location
NaN        79064
ALLAREA    10197
URBAN       6386
RURAL       6159
Name: count, dtype: int64

--- Sex ---
Missing: 37705
Unique values: 5
Sex
NaN        37705
FEMALE     23528
BOTHSEX    21844
MALE       18727
_O             2
Name: count, dtype: int64

--- Education level ---
Missing: 99463
Unique values: 3
Education level
NaN       99463
LOWSEC     1357
PRIMAR      986
Name: count, dtype: int64

--- Type of skill ---
Missing: 99463
Unique values: 3
Type of skill
NaN           99463
SKILL_MATH     1273
SKILL_READ     1070
Name: count, dtype: int64

--- Disability status ---
Missing: 93128
Unique values: 4
Disability status
NaN    93128
PWD     3060
_T      3043
PD      2575
Name: count, dtype: int64

--- Hazard type ---
Missing: 101806
Unique values: 1
Hazard type
NaN    101806
Name: count, dtype: int64

--- Quantile ---
Missing: 101089
Unique values: 2
Quantile
NaN    101089
B50       717
Name: count, dtype: int64

In [133]:
dimension_summary = (
    all_goals
    .groupby("SeriesCode")
    .agg(
        age=("Age", lambda x: x.notna().any()),
        location=("Location", lambda x: x.notna().any()),
        sex=("Sex", lambda x: x.notna().any()),
        education=("Education level", lambda x: x.notna().any()),
        skill=("Type of skill", lambda x: x.notna().any()),
        disability=("Disability status", lambda x: x.notna().any()),
        hazard=("Hazard type", lambda x: x.notna().any()),
        quantile=("Quantile", lambda x: x.notna().any())
    )
    .reset_index()
)

dimension_summary

,SeriesCode,age,location,sex,education,skill,disability,hazard,quantile
0,EG_ACS_ELEC,False,True,False,False,False,False,False,False
1,IC_GEN_MGTL,True,False,True,False,False,False,False,False
2,IC_GEN_MGTL_19ICLS,True,False,True,False,False,False,False,False
3,IC_GEN_MGTN,True,False,True,False,False,False,False,False
4,IC_GEN_MGTN_19ICLS,True,False,True,False,False,False,False,False
5,IT_MOB_2GNTWK,False,False,False,False,False,False,False,False
6,IT_MOB_3GNTWK,False,False,False,False,False,False,False,False
7,IT_MOB_4GNTWK,False,False,False,False,False,False,False,False
8,IT_MOB_5GNTWK,False,False,False,False,False,False,False,False
9,SE_TOT_PRFL,False,False,True,True,True,False,False,False
10,SH_DYN_IMRT,True,False,True,False,False,False,False,False
11,SH_DYN_IMRTN,True,False,True,False,False,False,False,False
12,SH_DYN_MORT,True,False,True,False,False,False,False,False
13,SH_DYN_MORTN,True,False,True,False,False,False,False,False
14,SH_STA_MORT,False,False,True,False,False,False,False,False
15,SI_POV_50MI,False,False,False,False,False,False,False,True
16,SI_POV_DAY1,True,True,True,False,False,False,False,False
17,SI_POV_EMP1,True,False,True,False,False,False,False,False
18,SL_TLF_UEM,True,False,True,False,False,False,False,False
19,SL_TLF_UEMDIS,True,False,True,False,False,True,False,False
20,SL_TLF_UEMDIS_19ICLS,True,False,True,False,False,True,False,False
21,SL_TLF_UEM_19ICLS,True,False,True,False,False,False,False,False
22,SN_ITK_DEFC,False,False,False,False,False,False,False,False
23,SN_ITK_DEFCN,False,False,False,False,False,False,False,False
24,SP_ACS_BSRVH2O,False,True,False,False,False,False,False,False
25,SP_ACS_BSRVSAN,False,True,False,False,False,False,False,False
26,VC_DSR_AFFCT,False,False,False,False,False,False,False,False
27,VC_DSR_DAFF,False,False,False,False,False,False,False,False
28,VC_DSR_IJILN,False,False,False,False,False,False,False,False
29,VC_DSR_MISS,False,False,False,False,False,False,False,False
30,VC_DSR_MMHN,False,False,False,False,False,False,False,False
31,VC_DSR_MORT,False,False,False,False,False,False,False,False
32,VC_DSR_MTMP,False,False,False,False,False,False,False,False
33,VC_DSR_PDAN,False,False,False,False,False,False,False,False
34,VC_DSR_PDLN,False,False,False,False,False,False,False,False
35,VC_DSR_PDYN,False,False,False,False,False,False,False,False

In [134]:
key_cols = [
    "SeriesCode",
    "GeoAreaName",
    "TimePeriod",
    "Age",
    "Location",
    "Sex",
    "Education level",
    "Type of skill",
    "Disability status",
    "Quantile"
]

duplicates = all_goals[
    all_goals.duplicated(key_cols, keep=False)
]

print("Duplicate rows:", len(duplicates))

Duplicate rows: 0

In [135]:
missing_series = all_goals[
    all_goals["SeriesCode"].isin([
        "EG_ACS_ELEC",
        "SN_ITK_DEFC",
        "SN_ITK_DEFCN"
    ])
]

missing_series.groupby(
    ["SeriesCode", "GeoAreaName"]
)["Value_numeric"].apply(lambda x: x.isna().sum())

SeriesCode    GeoAreaName
EG_ACS_ELEC   Afghanistan                                              0
              Albania                                                  0
              Algeria                                                  0
              American Samoa                                          30
              Andorra                                                  0
              Angola                                                   7
              Anguilla                                                20
              Antigua and Barbuda                                      0
              Argentina                                                0
              Armenia                                                  0
              Aruba                                                    0
              Australia                                                0
              Austria                                                  0
              Azerbaijan                                               0
              Bahamas                                                  0
              Bahrain                                                  0
              Bangladesh                                               0
              Barbados                                                 0
              Belarus                                                  0
              Belgium                                                  0
              Belize                                                   0
              Benin                                                    0
              Bermuda                                                  0
              Bhutan                                                   0
              Bolivia (Plurinational State of)                         0
              Bosnia and Herzegovina                                   0
              Botswana                                                 0
              Brazil                                                   0
              British Virgin Islands                                   0
              Brunei Darussalam                                        0
              Bulgaria                                                 0
              Burkina Faso                                             7
              Burundi                                                  0
              Cabo Verde                                               0
              Cambodia                                                 0
              Cameroon                                                 0
              Canada                                                   0
              Cayman Islands                                           0
              Central African Republic                                 0
              Chad                                                     1
              Chile                                                    0
              China                                                    0
              China, Hong Kong Special Administrative Region           0
              China, Macao Special Administrative Region               0
              Colombia                                                 0
              Comoros                                                  0
              Congo                                                    0
              Cook Islands                                            10
              Costa Rica                                               0
              Croatia                                                  0
              Cuba                                                     0
              Curaçao                                                  0
              Cyprus                                                   0
              Czechia                                                  0
              Côte d'Ivoire                                            0
              Democratic People's Republic of Korea                   20
              Democratic Republic of the Congo                         0
              Denmark                                                  0
              Djibouti                                                 1
              Dominica                                                10
              Dominican Republic                                       0
              Ecuador                                                  0
              Egypt                                                    0
              El Salvador                                              0
              Equatorial Guinea                                        0
              Eritrea                                                  0
              Estonia                                                  0
              Eswatini                                                 0
              Ethiopia                                                 0
              Faroe Islands                                            0
              Fiji                                                     0
              Finland                                                  0
              France                                                   0
              French Polynesia                                         0
              Gabon                                                    1
              Gambia                                                   2
              Georgia                                                  0
              Germany                                                  0
              Ghana                                                    0
              Gibraltar                                                0
              Greece                                                   0
              Greenland                                                0
              Grenada                                                 20
              Guam                                                     0
              Guatemala                                                0
              Guinea                                                   0
              Guinea-Bissau                                            0
              Guyana                                                   0
              Haiti                                                    4
              Honduras                                                 0
              Hungary                                                  0
              Iceland                                                  0
              India                                                    0
              Indonesia                                                0
              Iran (Islamic Republic of)                               0
              Iraq                                                     0
              Ireland                                                  0
              Isle of Man                                              0
              Israel                                                   0
              Italy                                                    0
              Jamaica                                                  0
              Japan                                                    0
              Jordan                                                   0
              Kazakhstan                                               0
              Kenya                                                    0
              Kiribati                                                 7
              Kuwait                                                   0
              Kyrgyzstan                                               0
              Lao People's Democratic Republic                         0
              Latvia                                                   0
              Lebanon                                                  0
              Lesotho                                                  1
              Liberia                                                  0
              Libya                                                   10
              Liechtenstein                                            0
              Lithuania                                                0
              Luxembourg                                               0
              Madagascar                                               2
              Malawi                                                   0
              Malaysia                                                 0
              Maldives                                                 0
              Mali                                                     1
              Malta                                                    0
              Marshall Islands                                         0
              Mauritania                                              10
              Mauritius                                                0
              Mexico                                                   0
              Micronesia (Federated States of)                         0
              Monaco                                                   0
              Mongolia                                                 0
              Montenegro                                               0
              Morocco                                                  0
              Mozambique                                               0
              Myanmar                                                  0
              Namibia                                                  1
              Naoero                                                   3
              Nepal                                                    3
              Netherlands (Kingdom of the)                             0
              New Caledonia                                            0
              New Zealand                                              0
              Nicaragua                                                0
              Niger                                                    0
              Nigeria                                                  0
              Niue                                                    10
              North Macedonia                                          0
              Northern Mariana Islands                                 0
              Norway                                                   0
              Oman                                                     0
              Pakistan                                                 0
              Palau                                                    0
              Panama                                                   3
              Papua New Guinea                                         0
              Paraguay                                                 0
              Peru                                                     0
              Philippines                                              0
              Poland                                                   0
              Portugal                                                 0
              Puerto Rico                                              0
              Qatar                                                    0
              Republic of Korea                                        0
              Republic of Moldova                                      0
              Romania                                                  0
              Russian Federation                                       0
              Rwanda                                                   0
              Saint Kitts and Nevis                                    0
              Saint Lucia                                              0
              Saint Martin (French Part)                               0
              Saint Vincent and the Grenadines                         0
              Samoa                                                    0
              San Marino                                               0
              Sao Tome and Principe                                    0
              Saudi Arabia                                             0
              Senegal                                                  0
              Serbia                                                   0
              Seychelles                                               0
              Sierra Leone                                             0
              Singapore                                                0
              Sint Maarten (Dutch part)                                0
              Slovakia                                                 0
              Slovenia                                                 0
              Solomon Islands                                          0
              Somalia                                                  1
              South Africa                                             0
              South Sudan                                              0
              Spain                                                    0
              Sri Lanka                                                0
              State of Palestine                                       0
              Sudan                                                    0
              Suriname                                                 0
              Sweden                                                   0
              Switzerland                                              0
              Syrian Arab Republic                                     0
              Tajikistan                                               0
              Thailand                                                 0
              Timor-Leste                                              0
              Togo                                                     0
              Tonga                                                    0
              Trinidad and Tobago                                      0
              Tunisia                                                  0
              Turkmenistan                                             0
              Turks and Caicos Islands                                 0
              Tuvalu                                                   0
              Türkiye                                                  0
              Uganda                                                   0
              Ukraine                                                  0
              United Arab Emirates                                     0
              United Kingdom of Great Britain and Northern Ireland     0
              United Republic of Tanzania                              0
              United States Virgin Islands                             0
              United States of America                                 0
              Uruguay                                                  0
              Uzbekistan                                               0
              Vanuatu                                                  0
              Venezuela (Bolivarian Republic of)                       0
              Viet Nam                                                 0
              Yemen                                                    1
              Zambia                                                   0
              Zimbabwe                                                 0
SN_ITK_DEFC   Afghanistan                                              0
              Albania                                                  0
              Algeria                                                  6
              Angola                                                   0
              Argentina                                                0
              Armenia                                                 10
              Australia                                               10
              Austria                                                 10
              Azerbaijan                                              10
              Bangladesh                                               0
              Barbados                                                 1
              Belarus                                                 10
              Belgium                                                 10
              Belize                                                   0
              Benin                                                    0
              Bolivia (Plurinational State of)                         0
              Bosnia and Herzegovina                                  10
              Botswana                                                 0
              Brazil                                                   6
              Bulgaria                                                 4
              Burkina Faso                                             0
              Cabo Verde                                               0
              Cambodia                                                 0
              Cameroon                                                 0
              Canada                                                  10
              Central African Republic                                 0
              Chad                                                     0
              Chile                                                    4
              China                                                   10
              Colombia                                                 0
              Comoros                                                  0
              Congo                                                    0
              Costa Rica                                              10
              Croatia                                                 10
              Cuba                                                     8
              Cyprus                                                  10
              Czechia                                                 10
              Côte d'Ivoire                                            0
              Democratic People's Republic of Korea                    6
              Democratic Republic of the Congo                         0
              Denmark                                                 10
              Djibouti                                                 0
              Dominica                                                 0
              Dominican Republic                                       1
              Ecuador                                                  0
              Egypt                                                    0
              El Salvador                                              0
              Estonia                                                 10
              Eswatini                                                 0
              Ethiopia                                                 0
              Fiji                                                     0
              Finland                                                 10
              France                                                  10
              French Polynesia                                         1
              Gabon                                                    0

In [136]:
all_goals[
    (all_goals["SeriesCode"].isin([
        "EG_ACS_ELEC",
        "SN_ITK_DEFC",
        "SN_ITK_DEFCN"
    ])) &
    (all_goals["Value_numeric"].isna())
][[
    "SeriesCode",
    "GeoAreaName",
    "TimePeriod",
    "Value",
    "Observation Status",
    "Nature",
    "Units"
]]

,SeriesCode,GeoAreaName,TimePeriod,Value,Observation Status,Nature,Units
18802,SN_ITK_DEFC,Algeria,2019,<2.5,E,E,PERCENT
18803,SN_ITK_DEFC,Algeria,2020,<2.5,E,E,PERCENT
18804,SN_ITK_DEFC,Algeria,2021,<2.5,E,E,PERCENT
18805,SN_ITK_DEFC,Algeria,2022,<2.5,E,E,PERCENT
18806,SN_ITK_DEFC,Algeria,2023,<2.5,E,E,PERCENT
18807,SN_ITK_DEFC,Algeria,2024,<2.5,E,E,PERCENT
18818,SN_ITK_DEFC,Azerbaijan,2015,<2.5,E,E,PERCENT
18819,SN_ITK_DEFC,Azerbaijan,2016,<2.5,E,E,PERCENT
18820,SN_ITK_DEFC,Azerbaijan,2017,<2.5,E,E,PERCENT
18821,SN_ITK_DEFC,Azerbaijan,2018,<2.5,E,E,PERCENT
18822,SN_ITK_DEFC,Azerbaijan,2019,<2.5,E,E,PERCENT
18823,SN_ITK_DEFC,Azerbaijan,2020,<2.5,E,E,PERCENT
18824,SN_ITK_DEFC,Azerbaijan,2021,<2.5,E,E,PERCENT
18825,SN_ITK_DEFC,Azerbaijan,2022,<2.5,E,E,PERCENT
18826,SN_ITK_DEFC,Azerbaijan,2023,<2.5,E,E,PERCENT
18827,SN_ITK_DEFC,Azerbaijan,2024,<2.5,E,E,PERCENT
18838,SN_ITK_DEFC,Australia,2015,<2.5,E,E,PERCENT
18839,SN_ITK_DEFC,Australia,2016,<2.5,E,E,PERCENT
18840,SN_ITK_DEFC,Australia,2017,<2.5,E,E,PERCENT
18841,SN_ITK_DEFC,Australia,2018,<2.5,E,E,PERCENT
18842,SN_ITK_DEFC,Australia,2019,<2.5,E,E,PERCENT
18843,SN_ITK_DEFC,Australia,2020,<2.5,E,E,PERCENT
18844,SN_ITK_DEFC,Australia,2021,<2.5,E,E,PERCENT
18845,SN_ITK_DEFC,Australia,2022,<2.5,E,E,PERCENT
18846,SN_ITK_DEFC,Australia,2023,<2.5,E,E,PERCENT
18847,SN_ITK_DEFC,Australia,2024,<2.5,E,E,PERCENT
18848,SN_ITK_DEFC,Austria,2015,<2.5,E,E,PERCENT
18849,SN_ITK_DEFC,Austria,2016,<2.5,E,E,PERCENT
18850,SN_ITK_DEFC,Austria,2017,<2.5,E,E,PERCENT
18851,SN_ITK_DEFC,Austria,2018,<2.5,E,E,PERCENT
18852,SN_ITK_DEFC,Austria,2019,<2.5,E,E,PERCENT
18853,SN_ITK_DEFC,Austria,2020,<2.5,E,E,PERCENT
18854,SN_ITK_DEFC,Austria,2021,<2.5,E,E,PERCENT
18855,SN_ITK_DEFC,Austria,2022,<2.5,E,E,PERCENT
18856,SN_ITK_DEFC,Austria,2023,<2.5,E,E,PERCENT
18857,SN_ITK_DEFC,Austria,2024,<2.5,E,E,PERCENT
18868,SN_ITK_DEFC,Armenia,2015,<2.5,E,E,PERCENT
18869,SN_ITK_DEFC,Armenia,2016,<2.5,E,E,PERCENT
18870,SN_ITK_DEFC,Armenia,2017,<2.5,E,E,PERCENT
18871,SN_ITK_DEFC,Armenia,2018,<2.5,E,E,PERCENT
18872,SN_ITK_DEFC,Armenia,2019,<2.5,E,E,PERCENT
18873,SN_ITK_DEFC,Armenia,2020,<2.5,E,E,PERCENT
18874,SN_ITK_DEFC,Armenia,2021,<2.5,E,E,PERCENT
18875,SN_ITK_DEFC,Armenia,2022,<2.5,E,E,PERCENT
18876,SN_ITK_DEFC,Armenia,2023,<2.5,E,E,PERCENT
18877,SN_ITK_DEFC,Armenia,2024,<2.5,E,E,PERCENT
18881,SN_ITK_DEFC,Barbados,2018,<2.5,E,E,PERCENT
18888,SN_ITK_DEFC,Belgium,2015,<2.5,E,E,PERCENT
18889,SN_ITK_DEFC,Belgium,2016,<2.5,E,E,PERCENT
18890,SN_ITK_DEFC,Belgium,2017,<2.5,E,E,PERCENT
18891,SN_ITK_DEFC,Belgium,2018,<2.5,E,E,PERCENT
18892,SN_ITK_DEFC,Belgium,2019,<2.5,E,E,PERCENT
18893,SN_ITK_DEFC,Belgium,2020,<2.5,E,E,PERCENT
18894,SN_ITK_DEFC,Belgium,2021,<2.5,E,E,PERCENT
18895,SN_ITK_DEFC,Belgium,2022,<2.5,E,E,PERCENT
18896,SN_ITK_DEFC,Belgium,2023,<2.5,E,E,PERCENT
18897,SN_ITK_DEFC,Belgium,2024,<2.5,E,E,PERCENT
18908,SN_ITK_DEFC,Bosnia and Herzegovina,2015,<2.5,E,E,PERCENT
18909,SN_ITK_DEFC,Bosnia and Herzegovina,2016,<2.5,E,E,PERCENT
18910,SN_ITK_DEFC,Bosnia and Herzegovina,2017,<2.5,E,E,PERCENT
18911,SN_ITK_DEFC,Bosnia and Herzegovina,2018,<2.5,E,E,PERCENT
18912,SN_ITK_DEFC,Bosnia and Herzegovina,2019,<2.5,E,E,PERCENT
18913,SN_ITK_DEFC,Bosnia and Herzegovina,2020,<2.5,E,E,PERCENT
18914,SN_ITK_DEFC,Bosnia and Herzegovina,2021,<2.5,E,E,PERCENT
18915,SN_ITK_DEFC,Bosnia and Herzegovina,2022,<2.5,E,E,PERCENT
18916,SN_ITK_DEFC,Bosnia and Herzegovina,2023,<2.5,E,E,PERCENT
18917,SN_ITK_DEFC,Bosnia and Herzegovina,2024,<2.5,E,E,PERCENT
18928,SN_ITK_DEFC,Brazil,2015,<2.5,E,E,PERCENT
18929,SN_ITK_DEFC,Brazil,2016,<2.5,E,E,PERCENT
18930,SN_ITK_DEFC,Brazil,2017,<2.5,E,E,PERCENT
18931,SN_ITK_DEFC,Brazil,2018,<2.5,E,E,PERCENT
18932,SN_ITK_DEFC,Brazil,2019,<2.5,E,E,PERCENT
18937,SN_ITK_DEFC,Brazil,2024,<2.5,E,E,PERCENT
18964,SN_ITK_DEFC,Bulgaria,2021,<2.5,E,E,PERCENT
18965,SN_ITK_DEFC,Bulgaria,2022,<2.5,E,E,PERCENT
18966,SN_ITK_DEFC,Bulgaria,2023,<2.5,E,E,PERCENT
18967,SN_ITK_DEFC,Bulgaria,2024,<2.5,E,E,PERCENT
18978,SN_ITK_DEFC,Belarus,2015,<2.5,E,E,PERCENT
18979,SN_ITK_DEFC,Belarus,2016,<2.5,E,E,PERCENT
18980,SN_ITK_DEFC,Belarus,2017,<2.5,E,E,PERCENT
18981,SN_ITK_DEFC,Belarus,2018,<2.5,E,E,PERCENT
18982,SN_ITK_DEFC,Belarus,2019,<2.5,E,E,PERCENT
18983,SN_ITK_DEFC,Belarus,2020,<2.5,E,E,PERCENT
18984,SN_ITK_DEFC,Belarus,2021,<2.5,E,E,PERCENT
18985,SN_ITK_DEFC,Belarus,2022,<2.5,E,E,PERCENT
18986,SN_ITK_DEFC,Belarus,2023,<2.5,E,E,PERCENT
18987,SN_ITK_DEFC,Belarus,2024,<2.5,E,E,PERCENT
19008,SN_ITK_DEFC,Canada,2015,<2.5,E,E,PERCENT
19009,SN_ITK_DEFC,Canada,2016,<2.5,E,E,PERCENT
19010,SN_ITK_DEFC,Canada,2017,<2.5,E,E,PERCENT
19011,SN_ITK_DEFC,Canada,2018,<2.5,E,E,PERCENT
19012,SN_ITK_DEFC,Canada,2019,<2.5,E,E,PERCENT
19013,SN_ITK_DEFC,Canada,2020,<2.5,E,E,PERCENT
19014,SN_ITK_DEFC,Canada,2021,<2.5,E,E,PERCENT
19015,SN_ITK_DEFC,Canada,2022,<2.5,E,E,PERCENT
19016,SN_ITK_DEFC,Canada,2023,<2.5,E,E,PERCENT
19017,SN_ITK_DEFC,Canada,2024,<2.5,E,E,PERCENT
19064,SN_ITK_DEFC,Chile,2021,<2.5,E,E,PERCENT
19065,SN_ITK_DEFC,Chile,2022,<2.5,E,E,PERCENT
19066,SN_ITK_DEFC,Chile,2023,<2.5,E,E,PERCENT
19067,SN_ITK_DEFC,Chile,2024,<2.5,E,E,PERCENT
19068,SN_ITK_DEFC,China,2015,<2.5,E,E,PERCENT
19069,SN_ITK_DEFC,China,2016,<2.5,E,E,PERCENT
19070,SN_ITK_DEFC,China,2017,<2.5,E,E,PERCENT
19071,SN_ITK_DEFC,China,2018,<2.5,E,E,PERCENT
19072,SN_ITK_DEFC,China,2019,<2.5,E,E,PERCENT
19073,SN_ITK_DEFC,China,2020,<2.5,E,E,PERCENT
19074,SN_ITK_DEFC,China,2021,<2.5,E,E,PERCENT
19075,SN_ITK_DEFC,China,2022,<2.5,E,E,PERCENT
19076,SN_ITK_DEFC,China,2023,<2.5,E,E,PERCENT
19077,SN_ITK_DEFC,China,2024,<2.5,E,E,PERCENT
19128,SN_ITK_DEFC,Costa Rica,2015,<2.5,E,E,PERCENT
19129,SN_ITK_DEFC,Costa Rica,2016,<2.5,E,E,PERCENT
19130,SN_ITK_DEFC,Costa Rica,2017,<2.5,E,E,PERCENT
19131,SN_ITK_DEFC,Costa Rica,2018,<2.5,E,E,PERCENT
19132,SN_ITK_DEFC,Costa Rica,2019,<2.5,E,E,PERCENT
19133,SN_ITK_DEFC,Costa Rica,2020,<2.5,E,E,PERCENT
19134,SN_ITK_DEFC,Costa Rica,2021,<2.5,E,E,PERCENT
19135,SN_ITK_DEFC,Costa Rica,2022,<2.5,E,E,PERCENT
19136,SN_ITK_DEFC,Costa Rica,2023,<2.5,E,E,PERCENT
19137,SN_ITK_DEFC,Costa Rica,2024,<2.5,E,E,PERCENT
19138,SN_ITK_DEFC,Croatia,2015,<2.5,E,E,PERCENT
19139,SN_ITK_DEFC,Croatia,2016,<2.5,E,E,PERCENT
19140,SN_ITK_DEFC,Croatia,2017,<2.5,E,E,PERCENT
19141,SN_ITK_DEFC,Croatia,2018,<2.5,E,E,PERCENT
19142,SN_ITK_DEFC,Croatia,2019,<2.5,E,E,PERCENT
19143,SN_ITK_DEFC,Croatia,2020,<2.5,E,E,PERCENT
19144,SN_ITK_DEFC,Croatia,2021,<2.5,E,E,PERCENT
19145,SN_ITK_DEFC,Croatia,2022,<2.5,E,E,PERCENT
19146,SN_ITK_DEFC,Croatia,2023,<2.5,E,E,PERCENT
19147,SN_ITK_DEFC,Croatia,2024,<2.5,E,E,PERCENT
19148,SN_ITK_DEFC,Cuba,2015,<2.5,E,E,PERCENT
19149,SN_ITK_DEFC,Cuba,2016,<2.5,E,E,PERCENT
19150,SN_ITK_DEFC,Cuba,2017,<2.5,E,E,PERCENT
19151,SN_ITK_DEFC,Cuba,2018,<2.5,E,E,PERCENT
19152,SN_ITK_DEFC,Cuba,2019,<2.5,E,E,PERCENT
19153,SN_ITK_DEFC,Cuba,2020,<2.5,E,E,PERCENT
19154,SN_ITK_DEFC,Cuba,2021,<2.5,E,E,PERCENT
19155,SN_ITK_DEFC,Cuba,2022,<2.5,E,E,PERCENT
19158,SN_ITK_DEFC,Cyprus,2015,<2.5,E,E,PERCENT
19159,SN_ITK_DEFC,Cyprus,2016,<2.5,E,E,PERCENT
19160,SN_ITK_DEFC,Cyprus,2017,<2.5,E,E,PERCENT
19161,SN_ITK_DEFC,Cyprus,2018,<2.5,E,E,PERCENT
19162,SN_ITK_DEFC,Cyprus,2019,<2.5,E,E,PERCENT
19163,SN_ITK_DEFC,Cyprus,2020,<2.5,E,E,PERCENT
19164,SN_ITK_DEFC,Cyprus,2021,<2.5,E,E,PERCENT
19165,SN_ITK_DEFC,Cyprus,2022,<2.5,E,E,PERCENT
19166,SN_ITK_DEFC,Cyprus,2023,<2.5,E,E,PERCENT
19167,SN_ITK_DEFC,Cyprus,2024,<2.5,E,E,PERCENT
19168,SN_ITK_DEFC,Czechia,2015,<2.5,E,E,PERCENT
19169,SN_ITK_DEFC,Czechia,2016,<2.5,E,E,PERCENT
19170,SN_ITK_DEFC,Czechia,2017,<2.5,E,E,PERCENT
19171,SN_ITK_DEFC,Czechia,2018,<2.5,E,E,PERCENT
19172,SN_ITK_DEFC,Czechia,2019,<2.5,E,E,PERCENT
19173,SN_ITK_DEFC,Czechia,2020,<2.5,E,E,PERCENT
19174,SN_ITK_DEFC,Czechia,2021,<2.5,E,E,PERCENT
19175,SN_ITK_DEFC,Czechia,2022,<2.5,E,E,PERCENT
19176,SN_ITK_DEFC,Czechia,2023,<2.5,E,E,PERCENT
19177,SN_ITK_DEFC,Czechia,2024,<2.5,E,E,PERCENT
19188,SN_ITK_DEFC,Denmark,2015,<2.5,E,E,PERCENT
19189,SN_ITK_DEFC,Denmark,2016,<2.5,E,E,PERCENT
19190,SN_ITK_DEFC,Denmark,2017,<2.5,E,E,PERCENT
19191,SN_ITK_DEFC,Denmark,2018,<2.5,E,E,PERCENT
19192,SN_ITK_DEFC,Denmark,2019,<2.5,E,E,PERCENT
19193,SN_ITK_DEFC,Denmark,2020,<2.5,E,E,PERCENT
19194,SN_ITK_DEFC,Denmark,2021,<2.5,E,E,PERCENT
19195,SN_ITK_DEFC,Denmark,2022,<2.5,E,E,PERCENT
19196,SN_ITK_DEFC,Denmark,2023,<2.5,E,E,PERCENT
19197,SN_ITK_DEFC,Denmark,2024,<2.5,E,E,PERCENT
19217,SN_ITK_DEFC,Dominican Republic,2024,<2.5,E,E,PERCENT
19248,SN_ITK_DEFC,Estonia,2015,<2.5,E,E,PERCENT
19249,SN_ITK_DEFC,Estonia,2016,<2.5,E,E,PERCENT
19250,SN_ITK_DEFC,Estonia,2017,<2.5,E,E,PERCENT
19251,SN_ITK_DEFC,Estonia,2018,<2.5,E,E,PERCENT
19252,SN_ITK_DEFC,Estonia,2019,<2.5,E,E,PERCENT
19253,SN_ITK_DEFC,Estonia,2020,<2.5,E,E,PERCENT
19254,SN_ITK_DEFC,Estonia,2021,<2.5,E,E,PERCENT
19255,SN_ITK_DEFC,Estonia,2022,<2.5,E,E,PERCENT
19256,SN_ITK_DEFC,Estonia,2023,<2.5,E,E,PERCENT
19257,SN_ITK_DEFC,Estonia,2024,<2.5,E,E,PERCENT
19268,SN_ITK_DEFC,Finland,2015,<2.5,E,E,PERCENT
19269,SN_ITK_DEFC,Finland,2016,<2.5,E,E,PERCENT
19270,SN_ITK_DEFC,Finland,2017,<2.5,E,E,PERCENT
19271,SN_ITK_DEFC,Finland,2018,<2.5,E,E,PERCENT
19272,SN_ITK_DEFC,Finland,2019,<2.5,E,E,PERCENT
19273,SN_ITK_DEFC,Finland,2020,<2.5,E,E,PERCENT
19274,SN_ITK_DEFC,Finland,2021,<2.5,E,E,PERCENT
19275,SN_ITK_DEFC,Finland,2022,<2.5,E,E,PERCENT
19276,SN_ITK_DEFC,Finland,2023,<2.5,E,E,PERCENT
19277,SN_ITK_DEFC,Finland,2024,<2.5,E,E,PERCENT
19278,SN_ITK_DEFC,France,2015,<2.5,E,E,PERCENT
19279,SN_ITK_DEFC,France,2016,<2.5,E,E,PERCENT
19280,SN_ITK_DEFC,France,2017,<2.5,E,E,PERCENT
19281,SN_ITK_DEFC,France,2018,<2.5,E,E,PERCENT
19282,SN_ITK_DEFC,France,2019,<2.5,E,E,PERCENT
19283,SN_ITK_DEFC,France,2020,<2.5,E,E,PERCENT
19284,SN_ITK_DEFC,France,2021,<2.5,E,E,PERCENT
19285,SN_ITK_DEFC,France,2022,<2.5,E,E,PERCENT
19286,SN_ITK_DEFC,France,2023,<2.5,E,E,PERCENT
19287,SN_ITK_DEFC,France,2024,<2.5,E,E,PERCENT
19294,SN_ITK_DEFC,French Polynesia,2021,<2.5,E,E,PERCENT
19327,SN_ITK_DEFC,Georgia,2024,<2.5,E,E,PERCENT
19338,SN_ITK_DEFC,Germany,2015,<2.5,E,E,PERCENT
19339,SN_ITK_DEFC,Germany,2016,<2.5,E,E,PERCENT
19340,SN_ITK_DEFC,Germany,2017,<2.5,E,E,PERCENT
19341,SN_ITK_DEFC,Germany,2018,<2.5,E,E,PERCENT
19342,SN_ITK_DEFC,Germany,2019,<2.5,E,E,PERCENT
19343,SN_ITK_DEFC,Germany,2020,<2.5,E,E,PERCENT
19344,SN_ITK_DEFC,Germany,2021,<2.5,E,E,PERCENT
19345,SN_ITK_DEFC,Germany,2022,<2.5,E,E,PERCENT
19346,SN_ITK_DEFC,Germany,2023,<2.5,E,E,PERCENT
19347,SN_ITK_DEFC,Germany,2024,<2.5,E,E,PERCENT
19368,SN_ITK_DEFC,Greece,2015,<2.5,E,E,PERCENT
19369,SN_ITK_DEFC,Greece,2016,<2.5,E,E,PERCENT
19370,SN_ITK_DEFC,Greece,2017,<2.5,E,E,PERCENT
19371,SN_ITK_DEFC,Greece,2018,<2.5,E,E,PERCENT
19372,SN_ITK_DEFC,Greece,2019,<2.5,E,E,PERCENT
19373,SN_ITK_DEFC,Greece,2020,<2.5,E,E,PERCENT
19374,SN_ITK_DEFC,Greece,2021,<2.5,E,E,PERCENT
19375,SN_ITK_DEFC,Greece,2022,<2.5,E,E,PERCENT
19376,SN_ITK_DEFC,Greece,2023,<2.5,E,E,PERCENT
19377,SN_ITK_DEFC,Greece,2024,<2.5,E,E,PERCENT
19404,SN_ITK_DEFC,Guyana,2021,<2.5,E,E,PERCENT
19405,SN_ITK_DEFC,Guyana,2022,<2.5,E,E,PERCENT
19406,SN_ITK_DEFC,Guyana,2023,<2.5,E,E,PERCENT
19407,SN_ITK_DEFC,Guyana,2024,<2.5,E,E,PERCENT
19428,SN_ITK_DEFC,Hungary,2015,<2.5,E,E,PERCENT
19429,SN_ITK_DEFC,Hungary,2016,<2.5,E,E,PERCENT
19430,SN_ITK_DEFC,Hungary,2017,<2.5,E,E,PERCENT
19431,SN_ITK_DEFC,Hungary,2018,<2.5,E,E,PERCENT
19432,SN_ITK_DEFC,Hungary,2019,<2.5,E,E,PERCENT
19433,SN_ITK_DEFC,Hungary,2020,<2.5,E,E,PERCENT
19434,SN_ITK_DEFC,Hungary,2021,<2.5,E,E,PERCENT
19435,SN_ITK_DEFC,Hungary,2022,<2.5,E,E,PERCENT
19436,SN_ITK_DEFC,Hungary,2023,<2.5,E,E,PERCENT
19437,SN_ITK_DEFC,Hungary,2024,<2.5,E,E,PERCENT
19438,SN_ITK_DEFC,Iceland,2015,<2.5,E,E,PERCENT
19439,SN_ITK_DEFC,Iceland,2016,<2.5,E,E,PERCENT
19440,SN_ITK_DEFC,Iceland,2017,<2.5,E,E,PERCENT
19441,SN_ITK_DEFC,Iceland,2018,<2.5,E,E,PERCENT
19442,SN_ITK_DEFC,Iceland,2019,<2.5,E,E,PERCENT
19443,SN_ITK_DEFC,Iceland,2020,<2.5,E,E,PERCENT
19444,SN_ITK_DEFC,Iceland,2021,<2.5,E,E,PERCENT
19445,SN_ITK_DEFC,Iceland,2022,<2.5,E,E,PERCENT
19446,SN_ITK_DEFC,Iceland,2023,<2.5,E,E,PERCENT
19447,SN_ITK_DEFC,Iceland,2024,<2.5,E,E,PERCENT
19488,SN_ITK_DEFC,Ireland,2015,<2.5,E,E,PERCENT
19489,SN_ITK_DEFC,Ireland,2016,<2.5,E,E,PERCENT
19490,SN_ITK_DEFC,Ireland,2017,<2.5,E,E,PERCENT
19491,SN_ITK_DEFC,Ireland,2018,<2.5,E,E,PERCENT
19492,SN_ITK_DEFC,Ireland,2019,<2.5,E,E,PERCENT
19493,SN_ITK_DEFC,Ireland,2020,<2.5,E,E,PERCENT
19494,SN_ITK_DEFC,Ireland,2021,<2.5,E,E,PERCENT
19495,SN_ITK_DEFC,Ireland,2022,<2.5,E,E,PERCENT
19496,SN_ITK_DEFC,Ireland,2023,<2.5,E,E,PERCENT
19497,SN_ITK_DEFC,Ireland,2024,<2.5,E,E,PERCENT
19498,SN_ITK_DEFC,Israel,2015,<2.5,E,E,PERCENT
19499,SN_ITK_DEFC,Israel,2016,<2.5,E,E,PERCENT
19500,SN_ITK_DEFC,Israel,2017,<2.5,E,E,PERCENT
19501,SN_ITK_DEFC,Israel,2018,<2.5,E,E,PERCENT
19502,SN_ITK_DEFC,Israel,2019,<2.5,E,E,PERCENT
19503,SN_ITK_DEFC,Israel,2020,<2.5,E,E,PERCENT
19504,SN_ITK_DEFC,Israel,2021,<2.5,E,E,PERCENT
19505,SN_ITK_DEFC,Israel,2022,<2.5,E,E,PERCENT
19506,SN_ITK_DEFC,Israel,2023,<2.5,E,E,PERCENT
19507,SN_ITK_DEFC,Israel,2024,<2.5,E,E,PERCENT
19508,SN_ITK_DEFC,Italy,2015,<2.5,E,E,PERCENT
19509,SN_ITK_DEFC,Italy,2016,<2.5,E,E,PERCENT
19510,SN_ITK_DEFC,Italy,2017,<2.5,E,E,PERCENT
19511,SN_ITK_DEFC,Italy,2018,<2.5,E,E,PERCENT
19512,SN_ITK_DEFC,Italy,2019,<2.5,E,E,PERCENT
19513,SN_ITK_DEFC,Italy,2020,<2.5,E,E,PERCENT
19514,SN_ITK_DEFC,Italy,2021,<2.5,E,E,PERCENT
19515,SN_ITK_DEFC,Italy,2022,<2.5,E,E,PERCENT
19516,SN_ITK_DEFC,Italy,2023,<2.5,E,E,PERCENT
19517,SN_ITK_DEFC,Italy,2024,<2.5,E,E,PERCENT
19538,SN_ITK_DEFC,Japan,2015,<2.5,E,E,PERCENT
19539,SN_ITK_DEFC,Japan,2016,<2.5,E,E,PERCENT
19540,SN_ITK_DEFC,Japan,2017,<2.5,E,E,PERCENT
19541,SN_ITK_DEFC,Japan,2018,<2.5,E,E,PERCENT
19542,SN_ITK_DEFC,Japan,2019,<2.5,E,E,PERCENT
19543,SN_ITK_DEFC,Japan,2020,<2.5,E,E,PERCENT
19544,SN_ITK_DEFC,Japan,2021,<2.5,E,E,PERCENT
19545,SN_ITK_DEFC,Japan,2022,<2.5,E,E,PERCENT
19546,SN_ITK_DEFC,Japan,2023,<2.5,E,E,PERCENT
19547,SN_ITK_DEFC,Japan,2024,<2.5,E,E,PERCENT
19554,SN_ITK_DEFC,Kazakhstan,2021,<2.5,E,E,PERCENT
19555,SN_ITK_DEFC,Kazakhstan,2022,<2.5,E,E,PERCENT
19556,SN_ITK_DEFC,Kazakhstan,2023,<2.5,E,E,PERCENT
19557,SN_ITK_DEFC,Kazakhstan,2024,<2.5,E,E,PERCENT
19582,SN_ITK_DEFC,Democratic People's Republic of Korea,2019,NaN,O,NaN,PERCENT
19583,SN_ITK_DEFC,Democratic People's Republic of Korea,2020,NaN,O,NaN,PERCENT
19584,SN_ITK_DEFC,Democratic People's Republic of Korea,2021,NaN,O,NaN,PERCENT
19585,SN_ITK_DEFC,Democratic People's Republic of Korea,2022,NaN,O,NaN,PERCENT
19586,SN_ITK_DEFC,Democratic People's Republic of Korea,2023,NaN,O,NaN,PERCENT
19587,SN_ITK_DEFC,Democratic People's Republic of Korea,2024,NaN,O,NaN,PERCENT
19588,SN_ITK_DEFC,Republic of Korea,2015,<2.5,E,E,PERCENT
19589,SN_ITK_DEFC,Republic of Korea,2016,<2.5,E,E,PERCENT
19590,SN_ITK_DEFC,Republic of Korea,2017,<2.5,E,E,PERCENT
19591,SN_ITK_DEFC,Republic of Korea,2018,<2.5,E,E,PERCENT
19592,SN_ITK_DEFC,Republic of Korea,2019,<2.5,E,E,PERCENT
19593,SN_ITK_DEFC,Republic of Korea,2020,<2.5,E,E,PERCENT
19594,SN_ITK_DEFC,Republic of Korea,2021,<2.5,E,E,PERCENT
19595,SN_ITK_DEFC,Republic of Korea,2022,<2.5,E,E,PERCENT
19596,SN_ITK_DEFC,Republic of Korea,2023,<2.5,E,E,PERCENT
19597,SN_ITK_DEFC,Republic of Korea,2024,<2.5,E,E,PERCENT
19598,SN_ITK_DEFC,Kuwait,2015,<2.5,E,E,PERCENT
19599,SN_ITK_DEFC,Kuwait,2016,<2.5,E,E,PERCENT
19600,SN_ITK_DEFC,Kuwait,2017,<2.5,E,E,PERCENT
19601,SN_ITK_DEFC,Kuwait,2018,<2.5,E,E,PERCENT
19602,SN_ITK_DEFC,Kuwait,2019,<2.5,E,E,PERCENT
19603,SN_ITK_DEFC,Kuwait,2020,<2.5,E,E,PERCENT
19604,SN_ITK_DEFC,Kuwait,2021,<2.5,E,E,PERCENT
19605,SN_ITK_DEFC,Kuwait,2022,<2.5,E,E,PERCENT
19606,SN_ITK_DEFC,Kuwait,2023,<2.5,E,E,PERCENT
19607,SN_ITK_DEFC,Kuwait,2024,<2.5,E,E,PERCENT
19638,SN_ITK_DEFC,Latvia,2015,<2.5,E,E,PERCENT
19639,SN_ITK_DEFC,Latvia,2016,<2.5,E,E,PERCENT
19640,SN_ITK_DEFC,Latvia,2017,<2.5,E,E,PERCENT
19641,SN_ITK_DEFC,Latvia,2018,<2.5,E,E,PERCENT
19642,SN_ITK_DEFC,Latvia,2019,<2.5,E,E,PERCENT
19643,SN_ITK_DEFC,Latvia,2020,<2.5,E,E,PERCENT
19644,SN_ITK_DEFC,Latvia,2021,<2.5,E,E,PERCENT
19645,SN_ITK_DEFC,Latvia,2022,<2.5,E,E,PERCENT
19646,SN_ITK_DEFC,Latvia,2023,<2.5,E,E,PERCENT
19647,SN_ITK_DEFC,Latvia,2024,<2.5,E,E,PERCENT
19668,SN_ITK_DEFC,Lithuania,2015,<2.5,E,E,PERCENT
19669,SN_ITK_DEFC,Lithuania,2016,<2.5,E,E,PERCENT
19670,SN_ITK_DEFC,Lithuania,2017,<2.5,E,E,PERCENT
19671,SN_ITK_DEFC,Lithuania,2018,<2.5,E,E,PERCENT
19672,SN_ITK_DEFC,Lithuania,2019,<2.5,E,E,PERCENT
19673,SN_ITK_DEFC,Lithuania,2020,<2.5,E,E,PERCENT
19674,SN_ITK_DEFC,Lithuania,2021,<2.5,E,E,PERCENT
19675,SN_ITK_DEFC,Lithuania,2022,<2.5,E,E,PERCENT
19676,SN_ITK_DEFC,Lithuania,2023,<2.5,E,E,PERCENT
19677,SN_ITK_DEFC,Lithuania,2024,<2.5,E,E,PERCENT
19678,SN_ITK_DEFC,Luxembourg,2015,<2.5,E,E,PERCENT
19679,SN_ITK_DEFC,Luxembourg,2016,<2.5,E,E,PERCENT
19680,SN_ITK_DEFC,Luxembourg,2017,<2.5,E,E,PERCENT
19681,SN_ITK_DEFC,Luxembourg,2018,<2.5,E,E,PERCENT
19682,SN_ITK_DEFC,Luxembourg,2019,<2.5,E,E,PERCENT
19683,SN_ITK_DEFC,Luxembourg,2020,<2.5,E,E,PERCENT
19684,SN_ITK_DEFC,Luxembourg,2021,<2.5,E,E,PERCENT
19685,SN_ITK_DEFC,Luxembourg,2022,<2.5,E,E,PERCENT
19686,SN_ITK_DEFC,Luxembourg,2023,<2.5,E,E,PERCENT
19687,SN_ITK_DEFC,Luxembourg,2024,<2.5,E,E,PERCENT
19714,SN_ITK_DEFC,Malaysia,2021,<2.5,E,E,PERCENT
19715,SN_ITK_DEFC,Malaysia,2022,<2.5,E,E,PERCENT
19716,SN_ITK_DEFC,Malaysia,2023,<2.5,E,E,PERCENT
19717,SN_ITK_DEFC,Malaysia,2024,<2.5,E,E,PERCENT
19728,SN_ITK_DEFC,Malta,2015,<2.5,E,E,PERCENT
19729,SN_ITK_DEFC,Malta,2016,<2.5,E,E,PERCENT
19730,SN_ITK_DEFC,Malta,2017,<2.5,E,E,PERCENT
19731,SN_ITK_DEFC,Malta,2018,<2.5,E,E,PERCENT
19732,SN_ITK_DEFC,Malta,2019,<2.5,E,E,PERCENT
19733,SN_ITK_DEFC,Malta,2020,<2.5,E,E,PERCENT
19734,SN_ITK_DEFC,Malta,2021,<2.5,E,E,PERCENT
19735,SN_ITK_DEFC,Malta,2022,<2.5,E,E,PERCENT
19736,SN_ITK_DEFC,Malta,2023,<2.5,E,E,PERCENT
19737,SN_ITK_DEFC,Malta,2024,<2.5,E,E,PERCENT
19776,SN_ITK_DEFC,Mongolia,2023,<2.5,E,E,PERCENT
19777,SN_ITK_DEFC,Mongolia,2024,<2.5,E,E,PERCENT
19780,SN_ITK_DEFC,Republic of Moldova,2017,<2.5,E,E,PERCENT
19781,SN_ITK_DEFC,Republic of Moldova,2018,<2.5,E,E,PERCENT
19782,SN_ITK_DEFC,Republic of Moldova,2019,<2.5,E,E,PERCENT
19783,SN_ITK_DEFC,Republic of Moldova,2020,<2.5,E,E,PERCENT
19784,SN_ITK_DEFC,Republic of Moldova,2021,<2.5,E,E,PERCENT
19785,SN_ITK_DEFC,Republic of Moldova,2022,<2.5,E,E,PERCENT
19786,SN_ITK_DEFC,Republic of Moldova,2023,<2.5,E,E,PERCENT
19787,SN_ITK_DEFC,Republic of Moldova,2024,<2.5,E,E,PERCENT
19788,SN_ITK_DEFC,Montenegro,2015,<2.5,E,E,PERCENT
19789,SN_ITK_DEFC,Montenegro,2016,<2.5,E,E,PERCENT
19790,SN_ITK_DEFC,Montenegro,2017,<2.5,E,E,PERCENT
19791,SN_ITK_DEFC,Montenegro,2018,<2.5,E,E,PERCENT
19792,SN_ITK_DEFC,Montenegro,2019,<2.5,E,E,PERCENT
19793,SN_ITK_DEFC,Montenegro,2020,<2.5,E,E,PERCENT
19794,SN_ITK_DEFC,Montenegro,2021,<2.5,E,E,PERCENT
19795,SN_ITK_DEFC,Montenegro,2022,<2.5,E,E,PERCENT
19796,SN_ITK_DEFC,Montenegro,2023,<2.5,E,E,PERCENT
19797,SN_ITK_DEFC,Montenegro,2024,<2.5,E,E,PERCENT
19848,SN_ITK_DEFC,Netherlands (Kingdom of the),2015,<2.5,E,E,PERCENT
19849,SN_ITK_DEFC,Netherlands (Kingdom of the),2016,<2.5,E,E,PERCENT
19850,SN_ITK_DEFC,Netherlands (Kingdom of the),2017,<2.5,E,E,PERCENT
19851,SN_ITK_DEFC,Netherlands (Kingdom of the),2018,<2.5,E,E,PERCENT
19852,SN_ITK_DEFC,Netherlands (Kingdom of the),2019,<2.5,E,E,PERCENT
19853,SN_ITK_DEFC,Netherlands (Kingdom of the),2020,<2.5,E,E,PERCENT
19854,SN_ITK_DEFC,Netherlands (Kingdom of the),2021,<2.5,E,E,PERCENT
19855,SN_ITK_DEFC,Netherlands (Kingdom of the),2022,<2.5,E,E,PERCENT
19856,SN_ITK_DEFC,Netherlands (Kingdom of the),2023,<2.5,E,E,PERCENT
19857,SN_ITK_DEFC,Netherlands (Kingdom of the),2024,<2.5,E,E,PERCENT
19878,SN_ITK_DEFC,New Zealand,2015,<2.5,E,E,PERCENT
19879,SN_ITK_DEFC,New Zealand,2016,<2.5,E,E,PERCENT
19880,SN_ITK_DEFC,New Zealand,2017,<2.5,E,E,PERCENT
19881,SN_ITK_DEFC,New Zealand,2018,<2.5,E,E,PERCENT
19882,SN_ITK_DEFC,New Zealand,2019,<2.5,E,E,PERCENT
19883,SN_ITK_DEFC,New Zealand,2020,<2.5,E,E,PERCENT
19884,SN_ITK_DEFC,New Zealand,2021,<2.5,E,E,PERCENT
19885,SN_ITK_DEFC,New Zealand,2022,<2.5,E,E,PERCENT

In [139]:
missing_check = all_goals[
    all_goals["SeriesCode"].isin([
        "EG_ACS_ELEC",
        "SN_ITK_DEFC",
        "SN_ITK_DEFCN"
    ])
].copy()

missing_check["Missing_Type"] = np.where(
    missing_check["Value"].isna(),
    "Actually missing",
    np.where(
        missing_check["Value_numeric"].isna(),
        "Non-numeric / threshold value",
        "Numeric"
    )
)

print(
    missing_check
    .groupby(["SeriesCode", "Missing_Type"])
    .size()
)

SeriesCode    Missing_Type
EG_ACS_ELEC   Actually missing                  186
              Numeric                          6354
SN_ITK_DEFC   Actually missing                   16
              Non-numeric / threshold value     578
              Numeric                          1096
SN_ITK_DEFCN  Actually missing                  594
              Non-numeric / threshold value     159
              Numeric                           937
dtype: int64